window.exteriorDatabase = [
  { id: 406, brand: 'BMW', compat: ['E90', 'E92'], category: 'Rear Spoilers', title: 'BMW E90 / E92 M3 Carbon Rear Roof Spoiler', price: '$259 USD', saved: '$120 USD', image: 'https://i.imgur.com/gS1NH3x.jpeg' },
  { id: 407, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Fender', title: 'BMW E90 / E92 / E93 M3 Carbon Front Fenders (OEM Style)', price: '$1539 USD', saved: '$120 USD', image: 'https://i.imgur.com/9t2uX0J.png' },
  { id: 408, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Mirror Covers', title: 'BMW E90 / E92 / E93 M3 Carbon Side Mirror Covers', price: '$279 USD', saved: '$50 USD', image: 'https://i.imgur.com/TEbSErJ.png' },
  { id: 409, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Hood', title: 'BMW E90 / E92 / E93 M3 Carbon Fiber Custom Engine Hood', price: '$1899 USD', saved: '$480 USD', image: 'https://i.imgur.com/BE1Pxv2.png' },
  { id: 410, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Fender', title: 'BMW E90 / E92 / E93 M3 Carbon Front Fenders (GT4 Style)', price: '$2189 USD', saved: '$120 USD', image: 'https://i.imgur.com/wCyui6k.png' },
  { id: 411, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Badges', title: 'BMW E90 / E92 / E93 M3 Carbon Front Kidney Grilles', price: '$299 USD', saved: '$50 USD', image: 'https://i.imgur.com/O6EKE7d.png' }, // 👑 撥亂反正：中網歸入 Badges 分類，Saved 綁定 $50
  { id: 412, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Rear Diffusers', title: 'BMW E90 / E92 / E93 M3 Carbon Rear Diffuser (Varis Style)', price: '$1199 USD', saved: '$220 USD', image: 'https://i.imgur.com/X6eZfDi.png' }, // 👑 修正：大件整條尾牙，Saved 精算對齊 $220
  { id: 413, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Rear Spoilers', title: 'BMW E90 / E92 / E93 M3 Carbon GT Wing Spoiler', price: '$609 USD', saved: '$220 USD', image: 'https://i.imgur.com/gOTrbfZ.jpeg' }, // 👑 修正：競技大GT Wing，打包屬大件，Saved 綁定 $220
  { id: 414, brand: 'BMW', compat: ['E92'], category: 'Rear Spoilers', title: 'BMW E92 M3 Carbon Rear Trunk Spoiler (PSM Style Spec)', price: '$429 USD', saved: '$120 USD', image: 'https://i.imgur.com/IPlHjKG.jpeg' }, // 👑 修正：普通尾翼中件，Saved 綁定 $120
  { id: 415, brand: 'BMW', compat: ['E92'], category: 'Rear Spoilers', title: 'BMW E92 M3 Carbon Rear Trunk Spoiler (CS Style Spec)', price: '$399 USD', saved: '$120 USD', image: 'https://i.imgur.com/m3AEJCY.png' }, // 👑 修正：普通尾翼中件，Saved 綁定 $120
  { id: 416, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Rear Diffusers', title: 'BMW E90 / E92 / E93 M3 Carbon Rear Bumper Side Splitters', price: '$299 USD', saved: '$50 USD', image: 'https://i.imgur.com/7VkGUNY.jpeg' }, // 👑 撥亂反正：後保包角屬於細件隨箱塞，歸入 Rear Diffusers 方便同底盤連動，Saved 綁定 $50
  { id: 417, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Other', title: 'BMW E90 / E92 / E93 M3 Carbon Front Bumper Canards', price: '$299 USD', saved: '$50 USD', image: 'https://i.imgur.com/ldN2j2B.jpeg' }, // 👑 修正：風翼細件，Saved 綁定 $50
  { id: 418, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Other', title: 'BMW E90 / E92 / E93 M3 Carbon Front Bumper Canards (GT4 Style)', price: '$299 USD', saved: '$50 USD', image: 'https://i.imgur.com/QUBm6yh.png' }, // 👑 修正：風翼細件，Saved 綁定 $50
  { id: 419, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (CRT Style)', price: '$509 USD', saved: '$220 USD', image: 'https://i.imgur.com/nEfcw2F.png' }, // 👑 修正：大件前唇，Saved 精算對齊 $220
  { id: 420, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Other', title: 'BMW E90 / E92 / E93 M3 Carbon Front Bumper Side Splitters', price: '$299 USD', saved: '$50 USD', image: 'https://i.imgur.com/UOpOoKG.jpeg' }, // 👑 修正：前包角小件，Saved 綁定 $50
  { id: 421, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Rear Diffusers', title: 'BMW E90 / E92 / E93 M3 Carbon Rear Diffuser (H2 Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/xAnBeSb.jpeg' }, // 👑 修正：大件橫跨式後唇，Saved 精算對齊 $220
  { id: 422, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Rear Diffusers', title: 'BMW E90 / E92 / E93 M3 Carbon Rear Diffuser (HA Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/xF1hbaJ.jpeg' }, // 👑 修正：大件橫跨式後唇，Saved 精算對齊 $220
  { id: 423, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Rear Diffusers', title: 'BMW E90 / E92 / M3 Carbon Rear Diffuser (V Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/kquaRtj.jpeg' }, // 👑 修正：大件橫跨式後唇，Saved 精算對齊 $220
  { id: 424, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Side Skirts', title: 'BMW E90 / E92 / E93 M3 Carbon Side Skit Extensions (EXOT Style)', price: '$629 USD', saved: '$220 USD', image: 'https://i.imgur.com/4hxQD2R.jpeg' }, // 👑 修正：大件側裙下長條，Saved 精算對齊 $220
  { id: 425, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (GT4 Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/wNBhwAA.jpeg' }, // 👑 修正：大件前唇，Saved 精算對齊 $220
  { id: 426, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (3D Style)', price: '$789 USD', saved: '$220 USD', image: 'https://i.imgur.com/ja7xFUk.jpeg' }, // 👑 修正：大件前唇，Saved 精算對齊 $220
  { id: 427, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (V Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/PpTUVjx.jpeg' }, // 👑 修正：大件前唇，Saved 精算對齊 $220
  { id: 428, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (AK Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/FFJgi74.jpeg' }, // 👑 修正：大件前唇，Saved 精算對齊 $220
  { id: 429, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (HA Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/i4b1aHo.jpeg' }, // 👑 修正：大件前唇，Saved 精算對齊 $220
  { id: 430, brand: 'BMW', compat: ['E90', 'E92', 'E93'], category: 'Front Lips', title: 'BMW E90 / E92 / E93 M3 Carbon Front Lip (GTS Style)', price: '$599 USD', saved: '$220 USD', image: 'https://i.imgur.com/7iikwKy.jpeg' }  // 👑 修正：大件前唇，Saved 精算對齊 $220
];
