/**
 * 🛠️ KINGZCARBON 核心外觀數據庫 (F 世代專屬分流數據庫檔案 - 2026 完全體 V3)
 * 💡 技術提示：變數必須直接掛載至 window 物件，確保前台跨域引擎完美讀取、絕不白屏！
 */ 

// 1. 底盤代號與品牌自動綁定集群 (F 世代專屬)
window.chassisMapping = {
  'BMW': [
    'F30 / F35 3-Series', 
    'F32 / F33 / F36 4-Series',
    'F34 3-Series GT', 
    'F10 / F18 5-Series',
    'F16 X6',
    'F87 M2 / M2C', 
    'F80 M3', 
    'F82 / F83 M4', 
    'F90 M5', 
    'F06 / F12 / F13 M6', 
    'F97 X3M / F98 X4M'
  ],
  'Toyota': [],
  'Nissan': []
};

// 2. 核心商品全庫存陣列 (1.8X倍率精算售價 + 免運優惠標籤 • 內嵌 Carbon)
window.exteriorDatabase = [
  // === 原有 F80/F82/F83 M3/M4 專屬集群數據 ===
  { id: 115, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (PSM Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/qrnGuXy.png' },
  { id: 116, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (R Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/F3Hd0r2.png' },
  { id: 117, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (3D Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/CoCsiSq.png' },
  { id: 118, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (Blade Style)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/qEVNTeI.png' },
  { id: 119, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (V Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/t6UEZip.png' },
  { id: 120, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (AC Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/v9j4bly.png' },
  { id: 121, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Splitters (AC Style Lite Edition)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/twBj4wn.png' },
  { id: 122, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (PSM Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/pyEwfHG.png' },
  { id: 123, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (PSM Dual-Layer Style)', price: '$779 USD', saved: '$205 USD', image: 'https://i.imgur.com/45wbJ8B.png' },
  { id: 124, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (CS Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/6lnCcNx.png' },
  { id: 125, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/L8Tt0vX.png' },
  { id: 126, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (R Style)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/aBCtbi6.png' },
  { id: 127, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (Varis Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/9scjvNX.png' },
  { id: 128, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (Laptorr Style)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/eCVCTCY.png' },
  { id: 129, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (3D Style)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/HMLHfl9.png' },
  { id: 130, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (GT4 Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/EaAeqv2.png' },
  { id: 131, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (V Style)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/mkbH1tR.png' },
  { id: 132, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (PSM Style With LED Light)', price: '$789 USD', saved: '$205 USD', image: 'https://i.imgur.com/Mg3BpAO.png' },
  { id: 133, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (3D Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/3yXUq9r.png' },
  { id: 134, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (CH Style With LED Light)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/rIPpydQ.png' },
  { id: 135, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (Varis Style)', price: '$979 USD', saved: '$205 USD', image: 'https://i.imgur.com/z3on1NN.png' },
  { id: 136, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (PSM Style)', price: '$789 USD', saved: '$205 USD', image: 'https://i.imgur.com/2Wp3vLo.png' },
  { id: 137, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Spoilers', title: 'BMW F80/F82 M3/M4 Carbon Rear Spoiler (PSM Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/59AHaeO.png' },
  { id: 138, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Spoilers', title: 'BMW F80/F82 M3/M4 Carbon Rear Spoiler (CS Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/eZgut4k.png' },
  { id: 139, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Spoilers', title: 'BMW F80/F82 M3/M4 Carbon Rear Spoiler (M4 Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/TwmQcsa.png' },
  { id: 140, brand: 'BMW', compat: ['F82', 'F83'], category: 'Trunk', title: 'BMW F82 M4 Carbon Fiber Trunk Lid (OEM Style)', price: '$1539 USD', saved: '$360 USD', image: 'https://i.imgur.com/7DCoR72.png' },
  { id: 141, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Hood', title: 'BMW F80/F82 M3/M4 Carbon Fiber Transparent Hood (Glass Style)', price: '$1789 USD', saved: '$360 USD', image: 'https://i.imgur.com/lzoObzG.png' },
  { id: 142, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Hood', title: 'BMW F80/F82 M3/M4 Carbon Fiber Hood (GTS Style)', price: '$1539 USD', saved: '$360 USD', image: 'https://i.imgur.com/HYcDgsl.png' },
  { id: 143, brand: 'BMW', compat: ['F82', 'F83'], category: 'Trunk', title: 'BMW F82 M4 Carbon Fiber Trunk Lid (CSL Style)', price: '$1789 USD', saved: '$360 USD', image: 'https://i.imgur.com/LP5wTIr.png' },
  { id: 144, brand: 'BMW', compat: ['F82', 'F83'], category: 'Front Fender', title: 'BMW F82 M4 Lightweight Carbon Fiber Front Fenders', price: '$1539 USD', saved: '$105 USD', image: 'https://i.imgur.com/d51eFkh.png' },
  { id: 145, brand: 'BMW', compat: ['F80'], category: 'Front Fender', title: 'BMW F80 M3 Lightweight Carbon Fiber Front Fenders', price: '$1539 USD', saved: '$105 USD', image: 'https://i.imgur.com/MulsV31.png' },
  { id: 146, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Mirror Covers', title: 'BMW F80/F82 M3/M4 Carbon Fiber Horn-Style Mirror Covers', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/wQQt4zz.png' },
  { id: 147, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Fiber Canards (C Style)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/A26hT46.png' },
  { id: 148, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Front Bumper Splitters (CH Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/1ju5fcm.png' },
  { id: 149, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Fiber Front Canards (CH Style)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/NwBBP29.png' },
  { id: 150, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Customizable Carbon Fiber Exhaust Tips', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/eBqLfC3.png' },
  { id: 151, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Full Carbon Fiber Front Kidney Grilles', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/8Q0W43Q.png' },
  { id: 152, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Full Carbon Fiber Seat Back Panels', price: '$599 USD', saved: '$105 USD', image: 'https://i.imgur.com/FZMPLBY.png' },
  { id: 153, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Bumper Canards (GT4 Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/rS2y3tE.png' },
  { id: 154, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Fiber Canards (MAD Style)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/R6ar2YY.png' },

  // === BMW F34 3-Series GT 專屬高性能改裝集群 ===
  { id: 155, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (H Style - M Sport Only)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/2Sjg728.jpeg' },
  { id: 156, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (KB Style - M Sport Only)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/rF60O4Q.jpeg' },
  { id: 157, brand: 'BMW', compat: ['F34'], category: 'Side Skirts', title: 'BMW 3-Series GT F34 Carbon Side Skirt Extensions (Blade Style - M Sport Only)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/oBDNsWL.jpeg' },
  { id: 158, brand: 'BMW', compat: ['F34'], category: 'Other', title: 'BMW 3-Series GT F34 Full Carbon Front Kidney Grille (Gloss Finish)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/Z6pbdS5.jpeg' },
  { id: 159, brand: 'BMW', compat: ['F34'], category: 'Rear Spoilers', title: 'BMW 3-Series GT F34 Carbon Fiber Rear Spoiler (CH Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/7Xs9uvt.jpeg' },
  { id: 160, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (PSM Style - Only for M4 Bumper Setup)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/UPJm10i.jpeg' },
  { id: 161, brand: 'BMW', compat: ['F34'], category: 'Other', title: 'BMW 3-Series GT F34 M4 Conversion Style Front & Rear Bumper Kit', price: '$1359 USD', saved: '$460 USD', image: 'https://i.imgur.com/WFObYaj.jpeg' },
  { id: 162, brand: 'BMW', compat: ['F34'], category: 'Other', title: 'BMW 3-Series GT F34 M-Tech Aero Full Body Kit Expansion Set', price: '$2259 USD', saved: '$460 USD', image: 'https://i.imgur.com/VEAnEuv.jpeg' },
  { id: 163, brand: 'BMW', compat: ['F34'], category: 'Rear Spoilers', title: 'BMW 3-Series GT F34 Carbon Fiber Rear Spoiler (3D Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/SrvUANj.jpeg' },
  { id: 164, brand: 'BMW', compat: ['F34'], category: 'Mirror Covers', title: 'BMW F34 GT Carbon Fiber M-Horn Style Side Mirror Covers', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/gu2C4tm.jpeg' },
  { id: 165, brand: 'BMW', compat: ['F34'], category: 'Side Skirts', title: 'BMW 3-Series GT F34 Carbon Side Skirt Extensions (MP Style - M Sport Only)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/ZGeeSH4.jpeg' },
  { id: 166, brand: 'BMW', compat: ['F34'], category: 'Rear Diffusers', title: 'BMW 3-Series GT F34 Carbon Rear Diffuser (KB Style - M Sport Only)', price: '$779 USD', saved: '$205 USD', image: 'https://i.imgur.com/A101CGQ.jpeg' },
  { id: 167, brand: 'BMW', compat: ['F34'], category: 'Rear Diffusers', title: 'BMW 3-Series GT F34 Carbon Rear Diffuser (M5 Style - M Sport Only)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/db7TcET.jpeg' },
  { id: 168, brand: 'BMW', compat: ['F34'], category: 'Rear Diffusers', title: 'BMW 3-Series GT F34 Carbon Rear Diffuser (MP Style - M Sport Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/YYYPekK.jpeg' },
  { id: 169, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (MP Style - M Sport Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/u7K4OeW.jpeg' },
  { id: 170, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (V Style - M Sport Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/7lYwwA5.jpeg' },

  // === BMW F90 M5 高階碳纖維集群 (已打通 G30/G38 5系列通用導流) ===
  { id: 171, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (CS Style - 2021-2023 LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/tFHchDh.jpeg' },
  { id: 172, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (RPK Style - 2021-2023 LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/r96qcpJ.jpeg' },
  { id: 173, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ML Style - 2021-2023 LCI)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/fzP1jpU.jpeg' },
  { id: 174, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ST Style - 2021-2023 LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/OBBPP9w.jpeg' },
  { id: 175, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (MT Style - 2021-2023 LCI)', price: '$779 USD', saved: '$205 USD', image: 'https://i.imgur.com/rTgFK3g.jpeg' },
  { id: 176, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (RPK Style - 2018-2020 Pre-LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/WPTMCJ1.jpeg' },
  { id: 177, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ML Style - 2018-2020 Pre-LCI)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/WTrhymT.jpeg' },
  { id: 178, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ST Style - 2018-2020 Pre-LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/kdMhLrU.jpeg' },
  { id: 179, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (GTS Style - 2018-2020 Pre-LCI)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/14y1YTq.jpeg' },
  { id: 180, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Carbon Front Bumper Splitters (CH Style - 2018-2020 Pre-LCI)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/VkZXmf6.jpeg' },
  { id: 181, brand: 'BMW', compat: ['F90'], category: 'Side Skirts', title: 'BMW F90 M5 Carbon Side Skirt Extensions (A Style - 2018-2020 Pre-LCI)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/ewakiuf.jpeg' },
  { id: 182, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (C Style - 2018-2020 Pre-LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/3pPus76.jpeg' },
  { id: 183, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (A Style - 2018-2020 Pre-LCI)', price: '$959 USD', saved: '$205 USD', image: 'https://i.imgur.com/nYjkIBA.jpeg' },
  { id: 184, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Rear Spoilers', title: 'BMW 5-Series & F90 M5 Carbon Rear Trunk Spoiler (M Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/IYbv9bR.jpeg' },
  { id: 185, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Rear Diffusers', title: 'BMW 5-Series & F90 M5 Carbon Rear Diffuser (3D Style)', price: '$879 USD', saved: '$205 USD', image: 'https://i.imgur.com/1k058Pd.jpeg' },
  { id: 186, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (CS Style - 2018-2020 Pre-LCI)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/kLLBkMl.jpeg' },
  { id: 187, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Rear Spoilers', title: 'BMW 5-Series & F90 M5 Carbon Rear Spoiler (PRO Style)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/8athyxb.jpeg' },
  { id: 188, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (V Style - 2018-2020 Pre-LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/XlxcUb2.jpeg' },
  { id: 189, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Roof Spoiler Extension (2018-2023 Universal)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/093hgWX.jpeg' },
  { id: 190, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Full Carbon Front Kidney Grille Surround (2018-2020 Pre-LCI)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/pRY6U5L.jpeg' },
  { id: 191, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Mirror Covers', title: 'BMW 5-Series & F90 M5 Carbon Fiber Side Mirror Covers', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/xivvHyV.jpeg' },
  { id: 192, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Carbon Rear Bumper Side Splitters (FD Style - 2018-2023 Universal)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/Q17Gz6C.jpeg' },
  { id: 193, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Carbon Rear Bumper Side Splitters (PSM Style - 2018-2023 Universal)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/MCSODjq.jpeg' },
  { id: 194, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (GTS Style - 2021-2023 LCI)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/goNURzx.jpeg' },
  { id: 195, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (P Style - 2021-2023 LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/BBlAbNn.jpeg' },
  { id: 196, brand: 'BMW', compat: ['F90'], category: 'Hood', title: 'BMW F90 M5 Motorsport Transparent Glass Carbon Fiber Hood (2018-2023 Universal)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/zbNygtH.jpeg' },
  { id: 197, brand: 'BMW', compat: ['F90'], category: 'Hood', title: 'BMW F90 M5 Carbon Fiber Ventilated GT Style Hood (2018-2023 Universal)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/V8oJLoN.jpeg' },
  { id: 198, brand: 'BMW', compat: ['F90'], category: 'Hood', title: 'BMW F90 M5 Lightweight CS Style Carbon Fiber Hood (2018-2023 Universal)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/GrDAPGe.jpeg' },
  { id: 199, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Front Bumper Foglight Canard Wings (2018-2020 Pre-LCI)', price: '$359 USD', saved: '$105 USD', image: 'https://i.imgur.com/Y9gmWEx.jpeg' },
  { id: 200, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Front Bumper Foglight Air Vent Inserts (2021-2023 LCI)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/e6xAqzP.jpeg' },
  { id: 201, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Other', title: 'BMW 5-Series & F90 M5 Full Carbon Front Kidney Grille (Gloss Finish)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/xDEQt9W.jpeg' },
  { id: 202, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (3D Style - 2018-2020 Pre-LCI)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/dTv62IQ.jpeg' },
  { id: 203, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (CH Style - 2018-2020 Pre-LCI)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/Bb9wxj5.jpeg' },
  { id: 204, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (Mode Style - 2018-2020 Pre-LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/7RKq1hO.jpeg' },
  { id: 205, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (MP Style - 2018-2020 Pre-LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/wk7nE2q.jpeg' },
  { id: 206, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Side Skirts', title: 'BMW 5-Series & F90 M5 Carbon Side Skirt Extensions (MP Style)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/Dab1KUg.jpeg' },
  { id: 207, brand: 'BMW', compat: ['F90'], category: 'Side Skirts', title: 'BMW F90 M5 Carbon Side Skirt Extensions (3D Style - 2018-2020 Pre-LCI)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/Rw9eFCR.jpeg' },
  { id: 208, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (A Style - 2018-2020 Pre-LCI)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/N9iitqs.jpeg' },
  { id: 209, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (A Style - 2021-2023 LCI)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/xjSweSy.jpeg' },
  { id: 210, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (3D Style - 2021-2023 LCI)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/dFE67jy.jpeg' },

  // === F90 M5 跨代新增空力組件與 5 系窄體/闊體轉換套件 ===
  { id: 257, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser Assembly (CH Style - Universal Fit)', price: '$1159 USD', saved: '$205 USD', image: 'https://i.imgur.com/890ayqX.jpeg' },
  { id: 258, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Customizable Muffler Exhaust Quad Tips Set', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/BGiLdBO.jpeg' },
  { id: 259, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 Pre-LCI Narrow Body Conversion Front Bumper Assembly', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/dS68gju.jpeg' },
  { id: 260, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Side Fender Air Vent Matte Accent Trims', price: '$349 USD', saved: '$105 USD', image: 'https://i.imgur.com/giq9285.jpeg' },
  { id: 261, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 Pre-LCI Wide Body Conversion Kit (Front Bumper & Front Fenders)', price: '$1729 USD', saved: '$360 USD', image: 'https://i.imgur.com/1FcKxky.jpeg' },
  { id: 262, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 LCI Narrow Body Conversion Front Bumper Assembly', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/g5F0Qe4.jpeg' },
  { id: 263, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 LCI Carbon Front Lip Spoiler (MP Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/evvWH80.jpeg' },
  { id: 264, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 LCI Wide Body Conversion Kit (Front Bumper & Front Fenders)', price: '$1729 USD', saved: '$360 USD', image: 'https://i.imgur.com/wuv5xBf.jpeg' },
  { id: 265, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 Pre-LCI Carbon Front Lip Center Section (MP Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/ExrCQCv.jpeg' },
  { id: 266, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 Pre-LCI Carbon Front Lip Spoiler (RKP Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/jtqihUN.jpeg' },

  // === BMW F87 M2 / M2C 高性能碳纖維集群 (V2 FORMULA UPDATED) ===
  { id: 211, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Splitters (MP Style - Pre-LCI & LCI Universal)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/Ny07GSd.png' },
  { id: 212, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (MP Style - Pre-LCI & LCI Universal)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/afytYVv.png' },
  { id: 213, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Competition Carbon Front Lip (3D Style - M2C Exclusive)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/XWupjPZ.png' },
  { id: 214, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (BP Style - Base M2 Exclusive)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/BV8YPLQ.png' },
  { id: 215, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (ST Style - Pre-LCI & LCI Universal)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/BV8YPLQ.png' },
  { id: 216, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (C Style - Pre-LCI & LCI Universal)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/p5CMFMP.png' },
  { id: 217, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Rear Side Splitters (MP Style)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/JCXAOv7.png' },
  { id: 218, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (Blade Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/Qmwmpvm.jpeg' },
  { id: 219, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (MTC Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Q5C6CT9.png' },
  { id: 220, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (CH Style)', price: '$659 USD', saved: '$205 USD', image: 'https://i.imgur.com/zx9pWHg.jpeg' },
  { id: 221, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (3D Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/rOiLJki.png' },
  { id: 222, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/zX8nxNw.jpeg' },
  { id: 223, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (AK Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/y90SlsZ.jpeg' },
  { id: 224, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser With LED F1 Brake Light (K Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/6UR3cjM.jpeg' },
  { id: 225, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser With LED F1 Brake Light (V Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/ttSh9vG.jpeg' },
  { id: 226, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (MP Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/xohdGJ9.png' },
  { id: 227, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (M4 Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/ceoIcva.jpeg' },
  { id: 228, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (CS Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/gQlMUiB.jpeg' },
  { id: 229, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (PSM Style)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/7pGx6re.jpeg' },
  { id: 230, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Motorsport High-Downforce Carbon Wing (MAD Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/WCmZnCm.jpeg' },
  { id: 231, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Track-Spec Carbon GT Wing (MP Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/EC8vaCO.png' },
  { id: 232, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Racing Carbon GT Wing (V Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/9EX2toR.jpeg' },
  { id: 233, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Front Bumper Side Aero Canard Accents (AC Style)', price: '$439 USD', saved: '$105 USD', image: 'https://i.imgur.com/BtS3hLa.png' },
  { id: 234, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 Carbon Kidney Grilles Trim Set (Base M2 Exclusive)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/BRTr42C.jpeg' },
  { id: 235, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Carbon Side Fender Emblem Badges Cover', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/JMZmAvX.jpeg' },
  { id: 236, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Quad Exhaust Carbon Fiber Tips Tailpipe Set (MP Style)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/1VcuXq3.jpeg' },
  { id: 237, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Front Grille Full Carbon Surround Shell Cover', price: '$659 USD', saved: '$105 USD', image: 'https://i.imgur.com/xu4VPRU.jpeg' },
  { id: 238, brand: 'BMW', compat: ['F87'], category: 'Hood', title: 'BMW F87 M2 / M2C Aggressive Ventilated Carbon Fiber Hood (GTS Style)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/IAEtawk.png' },
  { id: 239, brand: 'BMW', compat: ['F87'], category: 'Trunk', title: 'BMW F87 M2 / M2C Lightweight Full Carbon Fiber Trunk Lid (MP Style)', price: '$2009 USD', saved: '$360 USD', image: 'https://i.imgur.com/ecsJVDD.png' },
  { id: 240, brand: 'BMW', compat: ['F87'], category: 'Mirror Covers', title: 'BMW F87 M2 / M2C Carbon Fiber M-Horn Style Side Mirror Covers', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/wgjsqEd.jpeg' },
  { id: 241, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Full Carbon Performance Bucket Seat Back Shell Covers', price: '$599 USD', saved: '$105 USD', image: 'https://i.imgur.com/nbq1B41.jpeg' },
  { id: 242, brand: 'BMW', compat: ['F87'], category: 'Hood', title: 'BMW F87 M2 / M2C Performance Carbon Fiber Hood (MP Style)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/EHGrFiF.png' },
  { id: 243, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 M2C-Look Front Bumper Conversion Upgrade Kit', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/6VRSdqR.jpeg' },
  { id: 244, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 Front Bumper Foglight Splitter Aero Canards (Base M2 Exclusive)', price: '$319 USD', saved: '$105 USD', image: 'https://i.imgur.com/xYbD2c7.jpeg' },
  { id: 245, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (MTC Style - Pre-LCI & LCI Universal)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/cpmRAiq.png' },
  { id: 246, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (CS Style - Pre-LCI & LCI Universal)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/4rJ830V.png' },
  { id: 247, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (MTC Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/1Km71gQ.jpeg' },
  { id: 248, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (MTC Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/pEnQt7J.jpeg' },
  { id: 249, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (V Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/RIwtxWF.jpeg' },
  { id: 250, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Competition Carbon Front Lip (V Style - M2C Exclusive)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/tFLu71R.jpeg' },
  { id: 251, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (V Style - Base M2 Exclusive)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/9uXA05n.jpeg' },

  // === BMW M6 (F06 / F12 / F13) 高階碳纖維集群 ===
  { id: 252, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Other', title: 'BMW F06 / F12 / F13 M6 Carbon Front Kidney Grilles', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/9IRBnUx.jpeg' },
  { id: 253, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Mirror Covers', title: 'BMW F06 / F12 / F13 M6 Carbon Horn-Style Side Mirror Covers', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/SK0my1I.jpeg' },
  { id: 254, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Spoilers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Spoiler (V Style)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/vouoTh1.jpeg' },
  { id: 255, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Spoilers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Spoiler (MP Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/R6mer8u.jpeg' },
  { id: 256, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (PSM Style Heavy Work)', price: '$1249 USD', saved: '$360 USD', image: 'https://i.imgur.com/h4lNVeO.jpeg' },
  { id: 257, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (FD Style Aero Spec)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/tyFMQ1I.jpeg' },
  { id: 258, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (V Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/joh6zct.jpeg' },
  { id: 259, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (MP Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/h3dp2PB.jpeg' },
  { id: 260, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Side Skirts', title: 'BMW F06 / F12 / F13 M6 Carbon Side Skirt Extensions (V Style)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/3l623si.jpeg' },
  { id: 261, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (3D Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/dX7qmVa.png' },
  { id: 262, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (RPK Style)', price: '$689 USD', saved: '$205 USD', image: 'https://i.imgur.com/LeQOgzU.jpeg' },
  { id: 263, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (V1 Spec)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/nV7zHgU.jpeg' },
  { id: 264, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (V2 Spec)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/oFvbqi3.jpeg' },
  { id: 265, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (MP Style)', price: '$739 USD', saved: '$205 USD', image: 'https://i.imgur.com/fqPHyl7.jpeg' },
  { id: 266, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (H Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Z9XYXPk.jpeg' },

  // === BMW F97 X3M / F98 X4M 高階高性能集群 ===
  { id: 306, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (E Style V1)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/Qp26Ucs.png' },
  { id: 307, brand: 'BMW', compat: ['F97'], category: 'Rear Diffusers', title: 'BMW F97 X3M Carbon Rear Diffuser With LED F1 Brake Light (CH Style - X3M Exclusive)', price: '$919 USD', saved: '$205 USD', image: 'https://i.imgur.com/mJHGEgL.png' },
  { id: 308, brand: 'BMW', compat: ['F98'], category: 'Rear Diffusers', title: 'BMW F98 X4M Carbon Rear Diffuser (3D Style - X4M Exclusive)', price: '$969 USD', saved: '$205 USD', image: 'https://i.imgur.com/7ybk6Gs.png' },
  { id: 309, brand: 'BMW', compat: ['F97', 'F98'], category: 'Mirror Covers', title: 'BMW F97 X3M / F98 X4M Carbon Side Mirror Covers (M-Horn Style)', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/J4OJoPq.png' },
  { id: 310, brand: 'BMW', compat: ['F97'], category: 'Rear Spoilers', title: 'BMW F97 X3M Carbon Mid Roof Spoiler (C Style - X3M Exclusive)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/IkXjzUG.png' },
  { id: 311, brand: 'BMW', compat: ['F97'], category: 'Rear Spoilers', title: 'BMW F97 X3M Carbon Mid Roof Spoiler (E Style - X3M Exclusive)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/SC4AiAX.png' },
  { id: 312, brand: 'BMW', compat: ['F98'], category: 'Rear Spoilers', title: 'BMW F98 X4M Carbon Rear Trunk Spoiler (PSM Style - X4M Exclusive)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/PfPGQ0i.png' },
  { id: 313, brand: 'BMW', compat: ['F97', 'F98'], category: 'Hoods', title: 'BMW F97 X3M / F98 X4M Carbon Hood (CS Style)', price: '$1769 USD', saved: '$360 USD', image: 'https://i.imgur.com/fMKG5ic.png' },
  { id: 314, brand: 'BMW', compat: ['F97', 'F98'], category: 'Other', title: 'BMW F97 X3M / F98 X4M Carbon Front Kidney Grille Surround', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/t06JjcD.png' },
  { id: 315, brand: 'BMW', compat: ['F98'], category: 'Rear Spoilers', title: 'BMW F98 X4M Carbon Rear Trunk Spoiler (CS Style - X4M Exclusive)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/psd2Vo6.png' },
  { id: 316, brand: 'BMW', compat: ['F97'], category: 'Rear Spoilers', title: 'BMW F97 X3M Carbon Upper Roof Wing Extension (MP Style - X3M Exclusive)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/M3dVnX2.png' },
  { id: 317, brand: 'BMW', compat: ['F98'], category: 'Rear Diffusers', title: 'BMW F98 X4M Carbon Rear Diffuser With LED F1 Brake Light (CH Style - X4M Exclusive)', price: '$789 USD', saved: '$205 USD', image: 'https://i.imgur.com/xmKhwNR.png' },
  { id: 318, brand: 'BMW', compat: ['F97'], category: 'Rear Diffusers', title: 'BMW F97 X3M Carbon Rear Diffuser (E Style - X3M Exclusive)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/MXBlH46.png' },
  { id: 319, brand: 'BMW', compat: ['F97'], category: 'Rear Diffusers', title: 'BMW F97 X3M Carbon Rear Diffuser (3D Style - X3M Exclusive)', price: '$969 USD', saved: '$205 USD', image: 'https://i.imgur.com/6KOfURl.png' },
  { id: 320, brand: 'BMW', compat: ['F97', 'F98'], category: 'Side Skirts', title: 'BMW F97 X3M / F98 X4M Carbon Side Skirt Extensions (3D Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/dkc4UrY.png' },
  { id: 321, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (E Style V2)', price: '$689 USD', saved: '$205 USD', image: 'https://i.imgur.com/NmwTI2A.png' },
  { id: 322, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (JC Style)', price: '$969 USD', saved: '$205 USD', image: 'https://i.imgur.com/QligR0x.png' },
  { id: 323, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (ST Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/8S8Rv5d.png' },
  { id: 324, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (3D Style)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/PbQ7BUn.png' },

  // === BMW F10 / F18 5-Series 改 M5 外觀專屬集群 (V2 FORMULA) ===
  { id: 325, brand: 'BMW', compat: ['F10', 'F18'], category: 'Front Lips', title: 'BMW F10 / F18 5-Series Carbon Front Lip (RPK Style - Only For M5 Aftermarket Narrow Body Bumper Setup)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/4SRymQj.jpeg' },
  { id: 326, brand: 'BMW', compat: ['F10', 'F18'], category: 'Front Lips', title: 'BMW F10 / F18 5-Series Carbon Front Lip (H Style - Only For M5 Aftermarket Narrow Body Bumper Setup)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/lzytOUY.jpeg' },
  { id: 327, brand: 'BMW', compat: ['F10', 'F18'], category: 'Front Lips', title: 'BMW F10 / F18 5-Series Carbon Front Lip (3D Style - Only For M5 Aftermarket Narrow Body Bumper Setup)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/fyPRxyy.jpeg' },
  { id: 328, brand: 'BMW', compat: ['F10', 'F18'], category: 'Front Lips', title: 'BMW F10 / F18 5-Series Carbon Front Lip (V Style - Only For M5 Aftermarket Narrow Body Bumper Setup)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/ntNW6GA.jpeg' },
  { id: 329, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Diffusers', title: 'BMW F10 / F18 5-Series Carbon Rear Diffuser With LED F1 Brake Light (CH Style - Only For M5 Aftermarket Narrow Body Bumper Setup)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/Bo04AKu.jpeg' },
  { id: 330, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Diffusers', title: 'BMW F10 / F18 5-Series Carbon Rear Diffuser (PSM Style - Only For M5 Aftermarket Narrow Body Bumper Setup)', price: '$769 USD', saved: '$205 USD', image: 'https://i.imgur.com/8ynBi4Y.jpeg' },
  { id: 331, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Spoilers', title: 'BMW F10 / F18 5-Series Carbon Rear Spoiler (M Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/parN0u2.jpeg' },
  { id: 332, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Spoilers', title: 'BMW F10 / F18 5-Series Carbon Rear Spoiler (P Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/lZ0sMTT.jpeg' },
  { id: 333, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Spoilers', title: 'BMW F10 / F18 5-Series Carbon Rear Spoiler (V Style)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/Dwx9nol.jpeg' },
  { id: 334, brand: 'BMW', compat: ['F10', 'F18'], category: 'Mirror Covers', title: 'BMW F10 / F18 5-Series Carbon Side Mirror Covers (M-Horn Style)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/1Je7sdm.jpeg' },
  { id: 335, brand: 'BMW', compat: ['F10', 'F18'], category: 'Other', title: 'BMW F10 / F18 5-Series M5 Look Front Bumper Conversion Kit (Narrow Body Facelift Setup - Without Foglight)', price: '$899 USD', saved: '$460 USD', image: 'https://i.imgur.com/DGvZdp5.jpeg' },
  { id: 336, brand: 'BMW', compat: ['F10', 'F18'], category: 'Other', title: 'BMW F10 / F18 5-Series M5 Look Rear Bumper Conversion Kit (Narrow Body Facelift Setup)', price: '$899 USD', saved: '$460 USD', image: 'https://i.imgur.com/uFHZtyy.jpeg' },
  { id: 337, brand: 'BMW', compat: ['F10', 'F18'], category: 'Side Skirts', title: 'BMW F10 / F18 5-Series Carbon Side Skirt Extensions (3D Style - Only For M5 Aftermarket Narrow Body)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/o55JUMo.jpeg' },
  { id: 338, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Diffusers', title: 'BMW F10 / F18 5-Series Carbon Rear Diffuser (V Style - Only For M5 Aftermarket Narrow Body)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/wzIoDPJ.jpeg' },
  { id: 339, brand: 'BMW', compat: ['F10', 'F18'], category: 'Other', title: 'BMW F10 / F18 5-Series M5 Look Front Bumper Conversion Kit (Narrow Body Facelift Setup - With Foglight)', price: '$919 USD', saved: '$460 USD', image: 'https://i.imgur.com/oeV1SHO.jpeg' },
  { id: 340, brand: 'BMW', compat: ['F10', 'F18'], category: 'Other', title: 'BMW F10 / F18 5-Series Carbon Front Kidney Grilles (M5 Conversion Bumper Dedicated Only)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/AvLLdWY.jpeg' },
  { id: 341, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Spoilers', title: 'BMW F10 / F18 5-Series Carbon Roof Spoiler Extension', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/fliGTZs.jpeg' },
  { id: 342, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Spoilers', title: 'BMW F10 / F18 5-Series Carbon Rear Trunk Spoiler (PSM Style)', price: '$429 USD', saved: '$205 USD', image: 'https://i.imgur.com/9P9KMOa.jpeg' },
  { id: 343, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Spoilers', title: 'BMW F10 / F18 5-Series Carbon Rear Trunk Spoiler (M4 Heritage Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/Yq3MTgB.jpeg' },
  { id: 344, brand: 'BMW', compat: ['F10', 'F18'], category: 'Side Skirts', title: 'BMW F10 / F18 5-Series Carbon Side Skirt Extensions (Blade Style - Only For M5 Aftermarket Narrow Body)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/LRW3jU0.jpeg' },
  { id: 345, brand: 'BMW', compat: ['F10', 'F18'], category: 'Side Skirts', title: 'BMW F10 / F18 5-Series Carbon Side Skirt Extensions (PSM Style - Only For M5 Aftermarket Narrow Body)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/TlUHSua.jpeg' },
  { id: 346, brand: 'BMW', compat: ['F10', 'F18'], category: 'Rear Diffusers', title: 'BMW F10 / F18 5-Series Carbon Rear Diffuser (3D Style - Only For M5 Aftermarket Narrow Body)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/DQIWDab.jpeg' },

// === BMW F30 / F35 3-Series 高階改裝集群 ===
  { id: 367, brand: 'BMW', compat: ['F30', 'F35'], category: 'Rear Diffusers', title: 'BMW F30 / F35 3-Series Carbon Fiber Rear Diffuser (CH Style With LED F1 Brake Light - For M3 Aftermarket Bumper)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/EH1OMmu.jpeg' },
  { id: 368, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series GTS Style Hood (Premium Aluminum)', price: '$999 USD', saved: '$360 USD', image: 'https://i.imgur.com/yizkVdA.jpeg' },
  { id: 369, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series GTS Style Hood (Heavy Duty Pressed Steel)', price: '$929 USD', saved: '$360 USD', image: 'https://i.imgur.com/yizkVdA.jpeg' },
  { id: 370, brand: 'BMW', compat: ['F30', 'F35'], category: 'Hood', title: 'BMW F30 / F35 3-Series Custom Carbon Fiber Engine Hood (GTS Style)', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/IeZSQp3.jpeg' },
  { id: 371, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series High-Gloss Black Front Center Kidney Grilles (M3 Style)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/JYWo2rj.jpeg' },
  { id: 372, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Lip Spoiler (MP Style - Only For M3 Aftermarket Bumper Setup)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/f7JlpI1.jpeg' },
  { id: 373, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Lip Spoiler (V Style - Only For M3 Aftermarket Bumper Setup)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/xft4uLW.jpeg' },
  { id: 374, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Lip Spoiler (PSM Style - Only For M3 Aftermarket Bumper Setup)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/l08bCnJ.jpeg' },
  { id: 375, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Lip Spoiler (3D Style - Only For M3 Aftermarket Bumper Setup)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/WEPpuVE.jpeg' },
  { id: 376, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Lip Spoiler (R Style - Only For M3 Aftermarket Bumper Setup)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/TpeYuFI.jpeg' },
  { id: 377, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Lip Spoiler (Varis Style - Only For M3 Aftermarket Bumper Setup)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/3xrWzij.jpeg' },
  { id: 378, brand: 'BMW', compat: ['F30', 'F35'], category: 'Rear Diffusers', title: 'BMW F30 / F35 3-Series Carbon Fiber Rear Bumper Diffuser Lip (V Style - Only For M3 Aftermarket Bumper)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/3PcGmT9.jpeg' },
  { id: 379, brand: 'BMW', compat: ['F30', 'F35'], category: 'Side Skirts', title: 'BMW F30 / F35 3-Series Carbon Fiber Side Skirt Extensions (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/U2hStcx.jpeg' },
  { id: 380, brand: 'BMW', compat: ['F30', 'F35'], category: 'Side Skirts', title: 'BMW F30 / F35 3-Series Carbon Fiber Side Skirt Extensions (R Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/kLygxl9.jpeg' },
  { id: 381, brand: 'BMW', compat: ['F30', 'F35'], category: 'Mirror Covers', title: 'BMW F30 / F35 3-Series Carbon Fiber Side Mirror Covers (M-Horn Style Spec)', price: '$319 USD', saved: '$105 USD', image: 'https://i.imgur.com/E3vyYYv.jpeg' },
  { id: 382, brand: 'BMW', compat: ['F30'], category: 'Rear Spoilers', title: 'BMW F30 3-Series Carbon Rear Trunk Spoiler (M4 Style Spec)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/1mV3C7e.jpeg' },
  { id: 383, brand: 'BMW', compat: ['F30'], category: 'Rear Spoilers', title: 'BMW F30 3-Series Carbon Rear Trunk Spoiler (CS Style Spec)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/H16Ivb2.jpeg' },
  { id: 384, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series M3 Look Full Aerodynamic Conversion Body Kit Package (With Quad Exhaust Setup)', price: '$2449 USD', saved: '$460 USD', image: 'https://i.imgur.com/wT62TgP.jpeg' },
  { id: 3841, brand: 'BMW', compat: ['F30', 'F35'], category: 'Front Lips', title: 'BMW F30 / F35 3-Series Carbon Fiber Front Bumper Lip Spoiler (AC Style - Only For M3 Aftermarket Bumper Setup)', price: '$769 USD', saved: '$205 USD', image: 'https://i.imgur.com/JerruvN.jpeg' },
  { id: 3842, brand: 'BMW', compat: ['F30', 'F35'], category: 'Side Skirts', title: 'BMW F30 / F35 3-Series Carbon Fiber Side Skirt Extensions (Blade Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/pvk1CHQ.jpeg' },
  { id: 3843, brand: 'BMW', compat: ['F30', 'F35'], category: 'Side Skirts', title: 'BMW F30 / F35 3-Series Carbon Fiber Side Skirt Extensions (MTC Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/6gUGLKq.jpeg' },
  { id: 3844, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series Rear Bumper Side Apron Splitters (OTD Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/BYxROfN.jpeg' },
  { id: 3845, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series Front Bumper Side Vent Aerodynamic Canards Set', price: '$379 USD', saved: '$105 USD', image: 'https://i.imgur.com/jeRcA6s.jpeg' },
  { id: 3846, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series Rear Bumper Side Apron Splitters (PSM Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/EWQmEuX.jpeg' },
  { id: 3847, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series Rear Bumper Side Apron Splitters (L Style)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/olxdDhW.jpeg' },
  { id: 3848, brand: 'BMW', compat: ['F30', 'F35'], category: 'Other', title: 'BMW F30 / F35 3-Series Front Bumper Upper Corner Splitter Flaps Set', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/fIf6Vfi.jpeg' },
  
  // === BMW F32 / F33 / F36 4-Series 改 M4 外觀專屬集群 ===
  { id: 385, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (CC Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/2fOZRLk.jpeg' },
  { id: 386, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (MAD Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/WbVuSAv.jpeg' },
  { id: 387, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Side Skirts', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Skirt Extensions (MP Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/LhDtuIl.jpeg' },
  { id: 388, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Side Skirts', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Skirt Extensions (FD Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/BYFpi65.jpeg' },
  { id: 389, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Rear Diffusers', title: 'BMW F32 / F33 / F36 4-Series Carbon Rear Diffuser With LED F1 Brake Light (CH Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/rUHFdqB.jpeg' },
  { id: 390, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (M4 Style Spec)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/JILTPvJ.jpeg' },
  { id: 391, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (MP Style Spec)', price: '$629 USD', saved: '$105 USD', image: 'https://i.imgur.com/XoibaAj.jpeg' },
  { id: 392, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (MAD Style Spec)', price: '$629 USD', saved: '$105 USD', image: 'https://i.imgur.com/x72kJXv.jpeg' },
  { id: 393, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (V Style Spec)', price: '$629 USD', saved: '$105 USD', image: 'https://i.imgur.com/jB1MOYZ.jpeg' },
  { id: 394, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (PSM Style Spec)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/CF4eYa1.jpeg' },
  { id: 395, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (CS Style Spec)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/30HBpxD.jpeg' },
  { id: 396, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Other', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Kidney Grilles', price: '$299 USD', saved: '$105 USD', image: 'https://i.imgur.com/sn1i3em.jpeg' },
  { id: 397, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Mirror Covers', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Mirror Covers (M4 Horn Style)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/WWVochA.jpeg' },
  { id: 398, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Mirror Covers', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Mirror Covers (OEM Style)', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/VsrdmEy.jpeg' },
  { id: 399, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Other', title: 'BMW F32 / F33 / F36 4-Series Carbon Rear Bumper Side Splitters (MP Style)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/DjXD2EG.jpeg' },
  { id: 400, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Other', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Bumper Canards (CC Style)', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/fKL8bgW.jpeg' },
  { id: 401, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Rear Diffusers', title: 'BMW F32 / F33 / F36 4-Series Carbon Rear Diffuser (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/RXcBNp8.jpeg' },
  { id: 402, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Side Skirts', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Skirt Extensions (OT Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Mt1Xh3W.jpeg' },
  { id: 403, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Side Skirts', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Skirt Extensions (Blade Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/UBZ0sfJ.jpeg' },
  { id: 404, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (MP Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/3u1HDtH.jpeg' },
  { id: 405, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (FD Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/mhBE4G7.jpeg' },

  // === BMW F32 / F33 / F36 4-Series 改 M4 外觀包圍專用集群 ===
  { id: 469, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (CS Style - Coupe Spec)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/vkfW8PK.jpeg' },
  { id: 470, brand: 'BMW', compat: ['F32'], category: 'Rear Spoilers', title: 'BMW F32 4-Series Carbon Rear Trunk Spoiler (M4 Style - Coupe Spec)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/E2HJ3Zw.jpeg' },
  { id: 471, brand: 'BMW', compat: ['F32', 'F33'], category: 'Side Skirts', title: 'BMW F32 / F33 4-Series Carbon Side Skirt Extensions (MP Style - For M4 Bumper Conversion)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/aoHeKMd.jpeg' },
  { id: 472, brand: 'BMW', compat: ['F32', 'F33'], category: 'Side Skirts', title: 'BMW F32 / F33 4-Series Carbon Side Skirt Extensions (FD Style - For M4 Bumper Conversion)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Rtx8o4W.jpeg' },
  { id: 473, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Rear Diffusers', title: 'BMW F32 / F33 / F36 4-Series Carbon Rear Diffuser With LED Brake Light (CH Style - For M4 Bumper)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/04k24zz.jpeg' },
  { id: 474, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Rear Diffusers', title: 'BMW F32 / F33 / F36 4-Series Carbon Rear Diffuser (V Style - For M4 Bumper Conversion)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/oUbX8Rh.jpeg' },
  { id: 475, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (CS Style - For M4 Bumper Conversion)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/fkBCF1C.jpeg' },
  { id: 476, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (V Style - For M4 Bumper Conversion)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/5Lc7ORu.jpeg' },
  { id: 477, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (MP Style - For M4 Bumper Conversion)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/EFFOMNU.jpeg' },
  { id: 478, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Front Lips', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Lip (PSM Style - For M4 Bumper Conversion)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/EckfJtG.jpeg' },
  { id: 479, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Mirror Covers', title: 'BMW F32 / F33 / F36 4-Series Carbon Side Mirror Covers (M4 Horn Style)', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/XFj5Cgv.jpeg' },
  { id: 480, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Other', title: 'BMW F32 / F33 / F36 4-Series Carbon Front Kidney Grilles (M4 Style)', price: '$299 USD', saved: '$105 USD', image: 'https://i.imgur.com/J83Gflb.jpeg' },
  { id: 481, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Hoods', title: 'BMW F32 / F33 / F36 4-Series Carbon Fiber Custom Engine Hood (GTS Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/LO5wGKt.jpeg' },
  { id: 482, brand: 'BMW', compat: ['F32', 'F33'], category: 'Body Kits', title: 'BMW F32 / F33 4-Series To M4 Narrow Body Conversion Full Set (Front & Rear Bumpers, Fenders, Side Skirts)', price: '$1429 USD', saved: '$360 USD', image: 'https://i.imgur.com/RjiZBPO.jpeg' },
  { id: 483, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Fenders', title: 'BMW F32 / F33 / F36 4-Series To M4 Style Front Fenders (Pair)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/FiHlbz2.jpeg' },
  { id: 484, brand: 'BMW', compat: ['F32', 'F33'], category: 'Side Skirts', title: 'BMW F32 / F33 4-Series M4 Style Side Skirt Rocker Panels (Pair)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/QXjXuZl.jpeg' },
  { id: 485, brand: 'BMW', compat: ['F32', 'F33'], category: 'Body Kits', title: 'BMW F32 / F33 4-Series M4 Style Rear Bumper Assembly', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/XxmYOAN.jpeg' },
  { id: 486, brand: 'BMW', compat: ['F32', 'F33', 'F36'], category: 'Body Kits', title: 'BMW F32 / F33 / F36 4-Series M4 Style Front Bumper Assembly', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/FK8YtSo.jpeg' },

  // === BMW F90 M5 跨代新增空力組件與 5 系窄體/闊體轉換套件 ===
  { id: 469, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser Assembly (CH Style - Universal Fit)', price: '$1159 USD', saved: '$205 USD', image: 'https://i.imgur.com/890ayqX.jpeg' },
  { id: 470, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Customizable Muffler Exhaust Quad Tips Set', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/BGiLdBO.jpeg' },
  { id: 471, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 Pre-LCI Narrow Body Conversion Front Bumper Assembly', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/dS68gju.jpeg' },
  { id: 472, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Side Fender Air Vent Matte Accent Trims', price: '$349 USD', saved: '$105 USD', image: 'https://i.imgur.com/giq9285.jpeg' },
  { id: 473, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 Pre-LCI Wide Body Conversion Kit (Front Bumper & Front Fenders)', price: '$1729 USD', saved: '$360 USD', image: 'https://i.imgur.com/1FcKxky.jpeg' },
  { id: 474, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 LCI Narrow Body Conversion Front Bumper Assembly', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/g5F0Qe4.jpeg' },
  { id: 263, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 LCI Carbon Front Lip Spoiler (MP Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/evvWH80.jpeg' },
  { id: 264, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series To M5 LCI Wide Body Conversion Kit (Front Bumper & Front Fenders)', price: '$1729 USD', saved: '$360 USD', image: 'https://i.imgur.com/wuv5xBf.jpeg' },
  { id: 265, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 Pre-LCI Carbon Front Lip Center Section (MP Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/ExrCQCv.jpeg' },
  { id: 266, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 Pre-LCI Carbon Front Lip Spoiler (RKP Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/jtqihUN.jpeg' },
  { id: 500, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser Center Section (M5 Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/Zj7OUah.jpeg' },
  { id: 501, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Front Lips', title: 'BMW 5-Series & F90 M5 Pre-LCI Carbon Front Lip Spoiler (AC Style)', price: '$1129 USD', saved: '$205 USD', image: 'https://i.imgur.com/dEwV9iK.jpeg' },
  { id: 502, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Front Lips', title: 'BMW 5-Series & F90 M5 Pre-LCI Carbon Front Lip Spoiler (3D Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/vFkO3bQ.jpeg' },
  { id: 503, brand: 'BMW', compat: ['F90', 'G30', 'G38'], category: 'Other', title: 'BMW 5-Series & F90 M5 Pre-LCI Carbon Front Bumper Splitters (MP Style)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/R1F2vUY.jpeg' },

  // === BMW M6 (F06 / F12 / F13) 高階碳纖維集群 ===
  { id: 252, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Other', title: 'BMW F06 / F12 / F13 M6 Carbon Front Kidney Grilles', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/9IRBnUx.jpeg' },
  { id: 253, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Mirror Covers', title: 'BMW F06 / F12 / F13 M6 Carbon Horn-Style Side Mirror Covers', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/SK0my1I.jpeg' },
  { id: 254, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Spoilers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Spoiler (V Style)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/vouoTh1.jpeg' },
  { id: 255, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Spoilers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Spoiler (MP Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/R6mer8u.jpeg' },
  { id: 256, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (PSM Style Heavy Work)', price: '$1249 USD', saved: '$360 USD', image: 'https://i.imgur.com/h4lNVeO.jpeg' },
  { id: 257, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (FD Style Aero Spec)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/tyFMQ1I.jpeg' },
  { id: 258, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (V Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/joh6zct.jpeg' },
  { id: 259, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (MP Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/h3dp2PB.jpeg' },
  { id: 260, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Side Skirts', title: 'BMW F06 / F12 / F13 M6 Carbon Side Skirt Extensions (V Style)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/3l623si.jpeg' },
  { id: 261, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (3D Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/dX7qmVa.png' },
  { id: 262, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (RPK Style)', price: '$689 USD', saved: '$205 USD', image: 'https://i.imgur.com/LeQOgzU.jpeg' },
  { id: 263, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (V1 Spec)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/nV7zHgU.jpeg' },
  { id: 264, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (V2 Spec)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/oFvbqi3.jpeg' },
  { id: 265, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (MP Style)', price: '$739 USD', saved: '$205 USD', image: 'https://i.imgur.com/fqPHyl7.jpeg' },
  { id: 266, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (H Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Z9XYXPk.jpeg' },

  // === BMW F16 X6 高階外觀集群 (2015-2018) ===
  // --- Base Models / Standard Bumper 專屬分流 ---
  { id: 487, brand: 'BMW', compat: ['F16'], category: 'Front Lips', title: 'BMW X6 F16 Front Bumper Lip Spoiler (P Style - For Base Models Only)', price: '$769 USD', saved: '$205 USD', image: 'https://i.imgur.com/sUtPJXI.jpeg' },
  { id: 488, brand: 'BMW', compat: ['F16'], category: 'Rear Diffusers', title: 'BMW X6 F16 Rear Bumper Diffuser Lip (P Style - For Base Models Only)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/i5d8mhT.jpeg' },
  { id: 489, brand: 'BMW', compat: ['F16'], category: 'Other', title: 'BMW X6 F16 Rear Bumper Side Apron Splitters (P Style - For Base Models Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/OssdIE9.jpeg' },

  // --- M Sport Models / M-Tech Bumper 專屬分流 ---
  { id: 490, brand: 'BMW', compat: ['F16'], category: 'Front Lips', title: 'BMW X6 F16 Front Bumper Lip Spoiler (P Style - For M Sport Models Only)', price: '$769 USD', saved: '$205 USD', image: 'https://i.imgur.com/vGpli2U.jpeg' },
  { id: 491, brand: 'BMW', compat: ['F16'], category: 'Rear Diffusers', title: 'BMW X6 F16 Rear Bumper Diffuser Lip (P Style - For M Sport Models Only)', price: '$819 USD', saved: '$205 USD', image: 'https://i.imgur.com/gcp33Ex.jpeg' },
  { id: 492, brand: 'BMW', compat: ['F16'], category: 'Other', title: 'BMW X6 F16 Rear Bumper Side Apron Splitters (P Style - For M Sport Models Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/5Wc49Zx.jpeg' },

  // --- Universal Fit (All F16 X6 Models) 全通用集群 ---
  { id: 493, brand: 'BMW', compat: ['F16'], category: 'Other', title: 'BMW X6 F16 Side Fender Air Vent Duct Covers (Universal Fit)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/1KaRNLq.jpeg' },
  { id: 494, brand: 'BMW', compat: ['F16'], category: 'Other', title: 'BMW X6 F16 Front Headlight Eyelids Brows Cover (Universal Fit)', price: '$219 USD', saved: '$105 USD', image: 'https://i.imgur.com/Pxpq7hb.jpeg' },
  { id: 495, brand: 'BMW', compat: ['F16'], category: 'Mirror Covers', title: 'BMW X6 F16 Side Mirror Covers (Horn Style - Universal Fit)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/NG22fJn.jpeg' },
  { id: 496, brand: 'BMW', compat: ['F16'], category: 'Rear Spoilers', title: 'BMW X6 F16 Rear Trunk Spoiler Wing (P Style - Universal Fit)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/ml8sAPL.jpeg' },
  { id: 497, brand: 'BMW', compat: ['F16'], category: 'Rear Spoilers', title: 'BMW X6 F16 Rear Trunk Spoiler Wing (M Style - Universal Fit)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/vNhnUoq.jpeg' },
  { id: 498, brand: 'BMW', compat: ['F16'], category: 'Rear Spoilers', title: 'BMW X6 F16 Rear Trunk Spoiler Wing (PSM Style - Universal Fit)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/AjlizkU.jpeg' },
  { id: 499, brand: 'BMW', compat: ['F16'], category: 'Rear Spoilers', title: 'BMW X6 F16 Rear Upper Roof Wing Spoiler (H Style - Universal Fit)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/YmMOQ5a.jpeg' },

  // === BMW F85 X5M / F86 X6M 高性能 SUV 全通用集群 (供應商相容性對齊完全體) ===
  { id: 504, brand: 'BMW', compat: ['F85', 'F86'], category: 'Front Lips', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Front Bumper Lip Spoiler (3D Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/mUKFohS.jpeg' },
  { id: 505, brand: 'BMW', compat: ['F85', 'F86'], category: 'Front Lips', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Front Bumper Lip Spoiler (H Style)', price: '$459 USD', saved: '$105 USD', image: 'https://i.imgur.com/37AmcUs.jpeg' },
  { id: 506, brand: 'BMW', compat: ['F85', 'F86'], category: 'Front Lips', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Front Bumper Lip Spoiler (RPK Style)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/2j9iBFA.jpeg' },
  { id: 507, brand: 'BMW', compat: ['F85', 'F86'], category: 'Front Lips', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Front Bumper Lip Spoiler (V Style)', price: '$939 USD', saved: '$205 USD', image: 'https://i.imgur.com/e4aGMm8.jpeg' },
  { id: 508, brand: 'BMW', compat: ['F85', 'F86'], category: 'Side Skirts', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Side Skirt Extensions (MP Style)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/w3bmEud.jpeg' },
  { id: 509, brand: 'BMW', compat: ['F85', 'F86'], category: 'Side Skirts', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Side Skirt Extensions (3D Style)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/tQUCkv6.jpeg' },
  { id: 510, brand: 'BMW', compat: ['F85', 'F86'], category: 'Rear Diffusers', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Rear Bumper Diffuser Lip (3D Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/LdX44Uz.jpeg' },
  { id: 511, brand: 'BMW', compat: ['F85', 'F86'], category: 'Rear Diffusers', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Rear Bumper Diffuser Lip (V Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/NoC9zaC.jpeg' },
  { id: 512, brand: 'BMW', compat: ['F85', 'F86'], category: 'Rear Diffusers', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Rear Bumper Diffuser Lip (MP Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/B8RQpkb.jpeg' },
  { id: 513, brand: 'BMW', compat: ['F85', 'F86'], category: 'Rear Diffusers', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Rear Bumper Diffuser Lip (RPK Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/YWeMtZ0.jpeg' },
  { id: 514, brand: 'BMW', compat: ['F85', 'F86'], category: 'Mirror Covers', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Side Mirror Covers (M Style)', price: '$159 USD', saved: '$45 USD', image: 'https://i.imgur.com/8P1xogD.jpeg' },
  { id: 515, brand: 'BMW', compat: ['F85', 'F86'], category: 'Other', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Front Bumper Side Air Vent Shrouds', price: '$319 USD', saved: '$105 USD', image: 'https://i.imgur.com/3iYZf8L.jpeg' },
  { id: 516, brand: 'BMW', compat: ['F85', 'F86'], category: 'Other', title: 'BMW F85 X5M / F86 X6M Gloss Black Center Kidney Grilles', price: '$119 USD', saved: '$45 USD', image: 'https://i.imgur.com/9PKppHJ.jpeg' },
  { id: 517, brand: 'BMW', compat: ['F85', 'F86'], category: 'Rear Spoilers', title: 'BMW F85 X5M / F86 X6M Carbon Fiber Roof Spoiler Wing (RGD Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/pOENPVN.jpeg' }

  ];
