/**
 * 🛠️ KINGZCARBON 核心外觀數據庫 (G 世代專專屬分流數據庫檔案 - 2026 完全體 V3)
 * 💡 技術提示：變數必須直接掛載至 window 物件，確保前台跨域引擎完美讀取、絕不白屏！
 */ 

// ==========================================================================
// KINGZCARBON 全局統一車型選單配置矩陣 (跨檔案通用完全體)
// ==========================================================================
window.chassisMapping = {
  'BMW': [
    // === E 世代性能集群 ===
    'E90 / E92 / E93 M3',

    // === F 世代普通車系集群 ===
    'F30 / F35 3-Series', 
    'F32 / F33 / F36 4-Series',
    'F34 3-Series GT', 
    'F10 / F18 5-Series',
    'F15 X5', 
    'F16 X6',

    // === F 世代頂級 M-Power 集群 ===
    'F87 M2 / M2C', 
    'F80 M3', 
    'F82 / F83 M4', 
    'F90 M5', 
    'F06 / F12 / F13 M6', 
    'F97 X3M / F98 X4M',

    // === G 世代普通車系集群 ===
    'G42 2-Series',
    'G20 / G28 3-Series', 
    'G22 4-Series',
    'G26 4-Series Gran Coupe', 
    'G30 / G38 5-Series',
    'G05 X5',
    'G06 X6',
    'G07 X7',

    // === G 世代頂級 M-Power 集群 ===
    'G87 M2', 
    'G80 M3', 
    'G82 M4'
  ],
  'Toyota': ['A90 Supra'],
  'Nissan': ['R35 GTR']
};

// 2. 核心商品全庫存陣列 (1.8X倍率精算售價 + 免運優惠標籤 • 內嵌 Carbon)
window.exteriorDatabase = [
  // === BMW G80 M3 / G82 M4 高性能集群 ===
  { id: 17, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (R44 Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/jigDsLH.jpeg' },
  { id: 18, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (A Style)', price: '$939 USD', saved: '$205 USD', image: 'https://i.imgur.com/KnTzjy0.jpeg' },
  { id: 19, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Side Fender Vent Accents (CH Style)', price: '$359 USD', saved: '$105 USD', image: 'https://i.imgur.com/n5AEPtd.jpeg' },
  { id: 20, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/iiGKyb6.jpeg' },
  { id: 21, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (V Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/a5aBM5i.jpeg' },
  { id: 22, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (CSL Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/9AcReRW.jpeg' },
  { id: 23, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (R44 Gen 2 Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/ByUEuXQ.jpeg' },
  { id: 24, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (CT Style)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/vEYjveG.jpeg' },
  { id: 25, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bonnet Hood Vent Accents', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/tSTrM6q.jpeg' },
  { id: 26, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Engine Bay Full Carbon Fiber Cover', price: '$669 USD', saved: '$105 USD', image: 'https://i.imgur.com/orpeM2F.jpeg' },
  { id: 27, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Heavy-Duty Underbody Oil Cooler Guard Panel', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/UTzEdPU.jpeg' },
  { id: 28, brand: 'BMW', compat: ['G80'], category: 'Trunk', title: 'BMW G80 M3 Dedicated Carbon Fiber Trunk Lid (CSL Style)', price: '$2779 USD', saved: '$360 USD', image: 'https://i.imgur.com/ZpmJzpj.jpeg' },
  { id: 29, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Fender', title: 'BMW G80 M3 / G82 M4 Lightweight Carbon Fiber Front Fenders', price: '$2369 USD', saved: '$105 USD', image: 'https://i.imgur.com/kXYhH7S.jpeg' },
  { id: 30, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Fender', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Fenders with Cooling Vents', price: '$2329 USD', saved: '$105 USD', image: 'https://i.imgur.com/ihsn0vH.jpeg' },
  { id: 31, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 Lightweight Carbon Fiber Hood (CSL Style)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/BtKvfx5.jpeg' },
  { id: 32, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Transparent Hood (Glass Style)', price: '$2879 USD', saved: '$360 USD', image: 'https://i.imgur.com/idX3wMy.jpeg' },
  { id: 33, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Hood (ALP Style)', price: '$1049 USD', saved: '$360 USD', image: 'https://i.imgur.com/nfBDqcu.jpeg' },
  { id: 34, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 High-Clearance Carbon Fiber Hood (Power Style)', price: '$3029 USD', saved: '$360 USD', image: 'https://i.imgur.com/kl6mQRr.jpeg' },
  { id: 35, brand: 'BMW', compat: ['G80', 'G82'], category: 'Mirror Covers', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Side Mirror Covers', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/XRVthP9.jpeg' },
  { id: 36, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Roof Antenna Overlay Cover', price: '$219 USD', saved: '$105 USD', image: 'https://i.imgur.com/bCGcpVd.jpeg' },
  { id: 37, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (ALP Style)', price: '$1049 USD', saved: '$105 USD', image: 'https://i.imgur.com/OFDFqg1.jpeg' },
  { id: 38, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (ST Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/ORFs7UH.jpeg' },
  { id: 39, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (V Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/77Bs79b.jpeg' },
  { id: 40, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (CSL Style)', price: '$589 USD', saved: '$105 USD', image: 'https://i.imgur.com/0J5Vefg.jpeg' },
  { id: 41, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (PSM Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/Op8zNEZ.jpeg' },
  { id: 42, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (OEM Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/phEwENP.jpeg' },
  { id: 44, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (Adro Style)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/3Q1vnvf.jpeg' },
  { id: 45, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (B Style)', price: '$849 USD', saved: '$205 USD', image: 'https://i.imgur.com/TTf8aSs.jpeg' },
  { id: 46, brand: 'BMW', compat: ['G20', 'G28', 'G80'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series & G80 M3 Carbon Rear Spoiler (M3 Style)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/9iAsTaX.jpeg' },
  { id: 47, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (V Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/0yd8I34.jpeg' },
  { id: 48, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser Center Trim (OEM Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/Hd1iBrU.jpeg' },
  { id: 49, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Bumper Side Splitters (OEM Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/XXCIPz2.jpeg' },
  { id: 50, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Bumper Side Splitters (MP Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/WB3C1jT.jpeg' },
  { id: 51, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (RSC Style)', price: '$849 USD', saved: '$205 USD', image: 'https://i.imgur.com/ehgesTm.jpeg' },
  { id: 52, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (PSM Style With LED Light)', price: '$789 USD', saved: '$205 USD', image: 'https://i.imgur.com/Mg3BpAO.png' },
  { id: 53, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (3D Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/3yXUq9r.png' },
  { id: 54, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (CH Style With LED Light)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/rIPpydQ.png' },
  { id: 55, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (Varis Style)', price: '$979 USD', saved: '$205 USD', image: 'https://i.imgur.com/z3on1NN.png' },
  { id: 56, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (PSM Style)', price: '$789 USD', saved: '$205 USD', image: 'https://i.imgur.com/2Wp3vLo.png' },
  { id: 57, brand: 'BMW', compat: ['G80', 'G82'], category: 'Side Skirts', title: 'BMW G80 M3 / G82 M4 Carbon Side Skirt Extensions (3D Style)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/Kx7oESN.jpeg' },
  { id: 58, brand: 'BMW', compat: ['G80', 'G82'], category: 'Side Skirts', title: 'BMW G80 M3 / G82 M4 Carbon Side Skirt Extensions (MP Style)', price: '$809 USD', saved: '$205 USD', image: 'https://i.imgur.com/nxiIjdT.jpeg' },
  { id: 59, brand: 'BMW', compat: ['G80', 'G82'], category: 'Side Skirts', title: 'BMW G80 M3 / G82 M4 Carbon Side Skirt Extensions (R44 Style)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/WolcNCI.jpeg' },
  { id: 60, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Side Fender Vent Accents (MP Style)', price: '$359 USD', saved: '$105 USD', image: 'https://i.imgur.com/lW5rPRF.jpeg' },
  { id: 61, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Bumper Side Vent Inlets (R44 Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/HyD7HrL.jpeg' },
  { id: 62, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Bumper Side Vent Inlets (MP Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/5K4Ua4r.jpeg' },
  { id: 63, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (AC Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/dcRet1W.jpeg' },
  { id: 64, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (3D Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/cGNekA8.jpeg' },
  { id: 65, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (GT Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/tvR6Zj1.jpeg' },
  { id: 66, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (MP Style)', price: '$319 USD', saved: '$105 USD', image: 'https://i.imgur.com/bxBYUhW.jpeg' },
  { id: 67, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (3D Style)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/W4MqFSy.jpeg' },

  // === BMW G20 / G28 3-Series 底盤專屬集群 (Pre-LCI & LCI 完全體) ===
  { id: 68, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (T Style - 2020-2022 M Sport Package Only)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/IC8cBeD.jpeg' },
  { id: 69, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series LCI Carbon Front Lip (AO Style - Facelift 2023-2025)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/jPFPGY8.jpeg' },
  { id: 70, brand: 'BMW', compat: ['G20', 'G28'], category: 'Trunk', title: 'BMW G20 / G28 3-Series Carbon Fiber Trunk Lid (CSL Style - 2021-2023)', price: '$2779 USD', saved: '$360 USD', image: 'https://i.imgur.com/zuDUGl1.jpeg' },
  { id: 71, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW G20 / G28 3-Series Carbon Fiber Transparent Hood (Glass Style)', price: '$1809 USD', saved: '$360 USD', image: 'https://i.imgur.com/2Nlrn8F.jpeg' },
  { id: 72, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW G20 / G28 3-Series Carbon Fiber Hood (C Style)', price: '$1649 USD', saved: '$360 USD', image: 'https://i.imgur.com/YFQpKgO.jpeg' },
  { id: 73, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW G20 / G28 3-Series Carbon Fiber Hood (MBJ Style)', price: '$1539 USD', saved: '$360 USD', image: 'https://i.imgur.com/LJJqU3F.jpeg' },
  { id: 74, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW G20 / G28 3-Series Carbon Fiber Hood (IMP Style)', price: '$1539 USD', saved: '$360 USD', image: 'https://i.imgur.com/cS9kfOe.jpeg' },
  { id: 75, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW G20 / G28 3-Series Carbon Fiber Hood (CS Style - 2020-2023)', price: '$1539 USD', saved: '$360 USD', image: 'https://i.imgur.com/Rs3ttkE.jpeg' },
  { id: 76, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW G20 / G28 3-Series Carbon Fiber Hood (GTS Style - 2020-2023)', price: '$1539 USD', saved: '$360 USD', image: 'https://i.imgur.com/HbC0fsO.jpeg' },
  { id: 77, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Fender', title: 'BMW G20 / G28 3-Series Carbon Fender Panels with Cooling Vents (2020-2023)', price: '$1059 USD', saved: '$105 USD', image: 'https://i.imgur.com/qPdIi4S.jpeg' },
  { id: 78, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (GTS Style)', price: '$659 USD', saved: '$205 USD', image: 'https://i.imgur.com/rrSx9BJ.jpeg' },
  { id: 79, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (Hollow Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/TDk5zWz.jpeg' },
  { id: 80, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (PSM Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/2VwgxRl.jpeg' },
  { id: 81, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (PRO Style)', price: '$399 USD', saved: '$205 USD', image: 'https://i.imgur.com/BPXFu8t.jpeg' },
  { id: 82, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (CS Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/9pP6fHG.jpeg' },
  { id: 83, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (M4 Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/iNAbRto.jpeg' },
  { id: 84, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (MP Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/AN0iLGW.jpeg' },
  { id: 85, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW G20 / G28 3-Series Carbon Rear Spoiler (M Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/GiDRDzM.jpeg' },
  { id: 86, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW G20 / G28 3-Series Full Carbon Front Grille Surround', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/PeTFuJC.jpeg' },
  { id: 87, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series LCI Carbon Rear Bumper Side Splitters (AD Style - Facelift 2023-2025)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/s1gcZQw.jpeg' },
  { id: 88, brand: 'BMW', compat: ['G20', 'G28'], category: 'Mirror Covers', title: 'BMW G20 / G28 3-Series Carbon Fiber M-Horn Style Side Mirror Covers', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/HG4BaJP.jpeg' },
  { id: 89, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Rear Bumper Side Splitters (FD Style - 2020-2022)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/MjmvnMi.jpeg' },
  { id: 90, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Rear Bumper Vent Canard Accents (2020-2022)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/zFUTZef.jpeg' },
  { id: 91, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Bumper Vent Canard Accents (T Style - 2020-2022 M Sport Package Only)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/DuHQbcB.jpeg' },
  { id: 92, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Rear Diffuser (GS Style - 2020-2022 M Sport Package Only)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/ODgjmsh.jpeg' },
  { id: 93, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series Carbon Rear Diffuser With LED F1 Brake Light (T Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/4Auntu2.jpeg' },
  { id: 94, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Rear Diffuser With F1 LED Light (K Style - 2020-2022 M Sport Package Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/OByrF6v.jpeg' },
  { id: 95, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Rear Diffuser With F1 LED Light (CH Style - 2020-2022 M Sport Package Only)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/JXJxyFw.jpeg' },
  { id: 96, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Rear Diffuser (MP Style - 2020-2022 M Sport Package Only)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/ntTqekE.jpeg' },
  { id: 97, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series LCI Carbon Rear Diffuser (V Style - Facelift 2023-2025)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/OJBi0r7.jpeg' },
  { id: 98, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series LCI Carbon Rear Diffuser With F1 LED Light (T Style - Facelift 2023-2025)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/TPsT4JY.jpeg' },
  { id: 99, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series LCI Carbon Rear Diffuser With F1 LED Light (MP Style - Facelift 2023-2025)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/8rXGorU.jpeg' },
  { id: 100, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW G20 / G28 3-Series LCI Carbon Rear Diffuser With F1 LED Light (F Style - Facelift 2023-2025)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/ruwYIJV.jpeg' },
  { id: 101, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW G20 / G28 3-Series Carbon Side Skirt Extensions (AD Style)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/WTiNf0P.jpeg' },
  { id: 102, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW G20 / G28 3-Series Carbon Side Skirt Extensions (AD Style - M Sport Package Only)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/fsDPXjT.jpeg' },
  { id: 103, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW G20 / G28 3-Series Carbon Side Skirt Extensions (T Style - M Sport Package Only)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/Z62I1zx.jpeg' },
  { id: 104, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW G20 / G28 3-Series Carbon Side Skirt Extensions (3D Style - M Sport Package Only)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/TiGoNqM.jpeg' },
  { id: 105, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW G20 / G28 3-Series Carbon Side Skirt Extensions (MP Style - M Sport Package Only)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/xlFBJuB.jpeg' },
  { id: 106, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (AC Style - 2020-2022 M Sport Package Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/ADriIfS.jpeg' },
  { id: 107, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (CC Style - 2020-2022 M Sport Package Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/LgVCizS.jpeg' },
  { id: 108, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (AK Style - 2020-2022 M Sport Package Only)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/HeJjeEW.jpeg' },
  { id: 109, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (T Style - 2020-2022 M Sport Package Only)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/QjLVrN6.jpeg' },
  { id: 110, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (MP Style - 2020-2022 M Sport Package Only)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/GxgFiz8.jpeg' },
  { id: 111, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (A Style - 2020-2022)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/OT95bxj.jpeg' },
  { id: 112, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series Pre-LCI Carbon Front Lip (FD Style - 2020-2022)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/1r36ytA.jpeg' },
  { id: 113, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series LCI Carbon Fiber Front Lip Spoiler (MP Style - Facelift 2023-2025)', price: '$619 USD', saved: '$205 USD', image: 'https://i.imgur.com/sirnwfh.jpeg' },
  { id: 114, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW G20 / G28 3-Series LCI Carbon Fiber Front Lip Spoiler (3D Style - Facelift 2023-2025)', price: '$619 USD', saved: '$205 USD', image: 'https://i.imgur.com/avzbFis.jpeg' },
  { id: 1141, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Side Skirt Extensions (T Style)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/Rz8uq4M.jpeg' },
  { id: 1142, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Rear Diffuser (MP Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/7naceYf.jpeg' },
  { id: 1143, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Rear Diffuser (T Style)', price: '$829 USD', saved: '$205 USD', image: 'https://i.imgur.com/qdIUUzH.jpeg' },
  { id: 1144, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Trunk Spoiler (Pro Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/1TTYdaC.jpeg' },
  { id: 1145, brand: 'BMW', compat: ['G20', 'G28'], category: 'Mirror Covers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Side Mirror Covers (OEM Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/bPiIPU2.jpeg' },
  { id: 1146, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3 Series G20 / G28 LCI Quad Exhaust Tips Upgrade - Titanium (For Standard 3 Series LCI Only / Does NOT Fit Genuine M3)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/YRVEGOb.jpeg' },
  { id: 1147, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3 Series G20 / G28 LCI Quad Exhaust Tips Upgrade - Carbon Fiber Customizable (For Standard 3 Series LCI Only / Does NOT Fit Genuine M3)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/At9ME9N.jpeg' },
  { id: 1148, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Trunk Spoiler (M4 Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/CJp6PAi.jpeg' },
  { id: 1149, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Trunk Spoiler (MP Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/yh36ywH.jpeg' },
  { id: 1150, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Trunk Spoiler (V Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/5MF14HJ.jpeg' },
  { id: 1151, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Trunk Spoiler (PSM Style)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/Fe0ntQB.jpeg' },
  { id: 1152, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Trunk Spoiler (CS Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/0WyLftF.jpeg' },
  { id: 1153, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Front Kidney Grille (Double Slat)', price: '$549 USD', saved: '$205 USD', image: 'https://i.imgur.com/xnmv1DA.jpeg' },
  { id: 1154, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3 Series G20 / G28 LCI Gloss Black Front Kidney Grille (Single Slat)', price: '$369 USD', saved: '$105 USD', image: 'https://i.imgur.com/yYV7GnB.jpeg' },
  { id: 1155, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3 Series G20 / G28 LCI Diamond Starry Front Kidney Grille (Gloss Black Frame with Silver Dots)', price: '$369 USD', saved: '$105 USD', image: 'https://i.imgur.com/rKv0ELU.jpeg' },
  { id: 1156, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3 Series G20 / G28 LCI Diamond Starry Front Kidney Grille (Gloss Black Frame with Black Dots)', price: '$369 USD', saved: '$105 USD', image: 'https://i.imgur.com/ReF7FoN.jpeg' },
  { id: 1157, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Side Skirt Extensions (3D Style)', price: '$619 USD', saved: '$205 USD', image: 'https://i.imgur.com/iZG62Tu.jpeg' },
  { id: 1158, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3 Series G20 / G28 LCI Carbon Fiber Side Skirt Extensions (MP Style)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/uqjjIRd.jpeg' },
  
  // === BMW G87 M2 專屬高端外觀集群 ===
  { id: 267, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (V Style Spec)', price: '$1979 USD', saved: '$205 USD', image: 'https://i.imgur.com/ecQWmUG.jpeg' },
  { id: 268, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Underbody Protection Guard Shield', price: '$979 USD', saved: '$105 USD', image: 'https://i.imgur.com/D1RTfsR.jpeg' },
  { id: 269, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (R44 Spec)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/iMhXN72.jpeg' },
  { id: 270, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (AD Style Premium)', price: '$1599 USD', saved: '$205 USD', image: 'https://i.imgur.com/0sAyHYF.jpeg' },
  { id: 271, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (MP Style)', price: '$919 USD', saved: '$205 USD', image: 'https://i.imgur.com/sERjlZE.jpeg' },
  { id: 272, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (TAKD Style)', price: '$1439 USD', saved: '$205 USD', image: 'https://i.imgur.com/LjMsluP.jpeg' },
  { id: 273, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (V Style Premium)', price: '$1709 USD', saved: '$205 USD', image: 'https://i.imgur.com/qiXEUcD.jpeg' },
  { id: 274, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (OEM Style)', price: '$969 USD', saved: '$205 USD', image: 'https://i.imgur.com/x8D3tHi.png' },
  { id: 275, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (TAKD Style)', price: '$1439 USD', saved: '$205 USD', image: 'https://i.imgur.com/mCkq1XH.jpeg' },
  { id: 276, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Rear Spoiler (MP Style V1)', price: '$469 USD', saved: '$205 USD', image: 'https://i.imgur.com/24LpsnD.jpeg' },
  { id: 277, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon GT Wing With LED Light (GT Style)', price: '$3369 USD', saved: '$360 USD', image: 'https://i.imgur.com/mjndrQw.jpeg' },
  { id: 278, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Roof Spoiler Extension', price: '$969 USD', saved: '$205 USD', image: 'https://i.imgur.com/t8vtvJv.jpeg' },
  { id: 279, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Bumper Air Vent Accents (SQ Style)', price: '$969 USD', saved: '$105 USD', image: 'https://i.imgur.com/nZOUqnB.jpeg' },
  { id: 280, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Grille Center Mesh (MP Style)', price: '$829 USD', saved: '$105 USD', image: 'https://i.imgur.com/kIckmNs.jpeg' },
  { id: 281, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Grille Center Mesh (S Style)', price: '$969 USD', saved: '$105 USD', image: 'https://i.imgur.com/MRcJZCa.jpeg' },
  { id: 282, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Bumper Canards (MP Style)', price: '$649 USD', saved: '$105 USD', image: 'https://i.imgur.com/VsvOLgn.jpeg' },
  { id: 283, brand: 'BMW', compat: ['G87'], category: 'Mirror Covers', title: 'BMW G87 M2 Carbon Side Mirror Covers (OEM Plus Spec)', price: '$719 USD', saved: '$105 USD', image: 'https://i.imgur.com/O8EkXwy.jpeg' },
  { id: 284, brand: 'BMW', compat: ['G87'], category: 'Front Fender', title: 'BMW G87 M2 Carbon Front Fenders Side Panel Set (V Style)', price: '$2189 USD', saved: '$360 USD', image: 'https://i.imgur.com/WRIPi8i.jpeg' },
  { id: 285, brand: 'BMW', compat: ['G87'], category: 'Hood', title: 'BMW G87 M2 Carbon Hood Panel (V Style)', price: '$2739 USD', saved: '$360 USD', image: 'https://i.imgur.com/LTNNyce.jpeg' },
  { id: 286, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Roof Antenna Overlay Fin Cover', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/g7nS68W.jpeg' },
  { id: 287, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Trunk Spoiler (MP Style V2)', price: '$1029 USD', saved: '$205 USD', image: 'https://i.imgur.com/hVzDOc7.jpeg' },
  { id: 288, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (MP Style)', price: '$969 USD', saved: '$205 USD', image: 'https://i.imgur.com/yFTJjof.jpeg' },
  { id: 289, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (V Style High-Gloss)', price: '$1479 USD', saved: '$205 USD', image: 'https://i.imgur.com/WtIw3cs.jpeg' },
  { id: 290, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Seat Back Shell Covers Set', price: '$1129 USD', saved: '$105 USD', image: 'https://i.imgur.com/bkA7j0G.jpeg' },
  { id: 291, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Rear Bumper Side Splitters (MP Style)', price: '$649 USD', saved: '$105 USD', image: 'https://i.imgur.com/dfZlsSX.jpeg' },
  { id: 292, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Bumper Lower Side Splitters (TAKD Style)', price: '$599 USD', saved: '$105 USD', image: 'https://i.imgur.com/aZ1hTbT.jpeg' },
  { id: 293, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Grille Center Trim (CSL Style)', price: '$719 USD', saved: '$105 USD', image: 'https://i.imgur.com/lZIsQpm.jpeg' },
  { id: 294, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Rear Bumper Wheel Vent Trim Covers (MP Style)', price: '$719 USD', saved: '$105 USD', image: 'https://i.imgur.com/oAykQQg.jpeg' },
  { id: 295, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Bumper Side Intake Shrouds (MP Style)', price: '$879 USD', saved: '$105 USD', image: 'https://i.imgur.com/f2789UJ.jpeg' },
  { id: 296, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Trunk Racing GT Wing (CH Style)', price: '$2249 USD', saved: '$205 USD', image: 'https://i.imgur.com/aZU5nMF.jpeg' },
  { id: 297, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Rear Spoiler (VS Style)', price: '$469 USD', saved: '$205 USD', image: 'https://i.imgur.com/nOPJrY2.jpeg' },
  { id: 298, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (CH Style Spec)', price: '$1709 USD', saved: '$205 USD', image: 'https://i.imgur.com/qqyLiNa.jpeg' },
  { id: 299, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Center-Exhaust Carbon Rear Diffuser (MP Style Setup Only)', price: '$1029 USD', saved: '$205 USD', image: 'https://i.imgur.com/jaCIzaI.png' },
  { id: 300, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (ADRO Style Track Edition)', price: '$1249 USD', saved: '$205 USD', image: 'https://i.imgur.com/LRWYtpE.jpeg' },
  { id: 301, brand: 'BMW', compat: ['G87'], category: 'Front Fender', title: 'BMW G87 M2 Carbon Front Fenders Side Panel Set (N Carbon Racing)', price: '$2189 USD', saved: '$360 USD', image: 'https://i.imgur.com/MAedKMC.jpeg' },
  { id: 302, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (R44 Design)', price: '$979 USD', saved: '$205 USD', image: 'https://i.imgur.com/Va84zJf.jpeg' },
  { id: 303, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Engine Bay Carbon Full Engine Cover Overlay', price: '$879 USD', saved: '$105 USD', image: 'https://i.imgur.com/IRQYqJ2.jpeg' },
  { id: 304, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (TAKD Style Premium)', price: '$1159 USD', saved: '$205 USD', image: 'https://i.imgur.com/GEuNQqf.jpeg' },
  { id: 305, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (R44 Design)', price: '$1129 USD', saved: '$205 USD', image: 'https://i.imgur.com/cTTXChh.jpeg' },

  // === BMW G30 / G38 5-Series M Sport 專屬集群 ===
  { id: 431, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (ED Style - Pre-LCI 2018-2020)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/tZlhmvr.jpeg' },
  { id: 432, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (3D Style - LCI 2021+)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/uA2u2IC.jpeg' },
  { id: 433, brand: 'BMW', compat: ['G30', 'G38'], category: 'Side Skirts', title: 'BMW G30 / G38 5-Series Carbon Side Skirt Extensions (3D Style)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/Kk3QyNG.jpeg' },
  { id: 434, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (MP Style - Pre-LCI 2018-2020)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Gs98HEH.jpeg' },
  { id: 435, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (C Style - Pre-LCI 2018-2020)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/YMYrmsm.jpeg' },
  { id: 436, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Front Grille (Dual Slat / Single Slat Selectable - LCI 2021+)', price: '$349 USD', saved: '$105 USD', image: 'https://i.imgur.com/gR3FkYQ.jpeg' },
  { id: 437, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Front Grille (Dual Slat / Single Slat Selectable - Pre-LCI 2018-2020)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/6PPEWle.jpeg' },
  { id: 438, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (HA Style - Pre-LCI 2018-2020)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/gxAwo4o.jpeg' },
  { id: 439, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (3D Style - Pre-LCI 2018-2020)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/Ze7Hbjv.jpeg' },
  { id: 440, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (CC Style - Pre-LCI 2018-2020)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Q8MeT9L.jpeg' },
  { id: 441, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (AC Style - Pre-LCI 2018-2020)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/SGevkuN.jpeg' },
  { id: 442, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (P Style - LCI 2021+)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/ZGbxSXU.jpeg' },
  { id: 443, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (Blade Style - LCI 2021+)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/1mWx6Kc.jpeg' },
  { id: 444, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (FD Style - Pre-LCI 2018-2020)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/HZzc4gR.jpeg' },
  { id: 445, brand: 'BMW', compat: ['G30', 'G38'], category: 'Side Skirts', title: 'BMW G30 / G38 5-Series Carbon Side Skirt Extensions (MP Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/bKiPwcD.jpeg' },
  { id: 446, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (MP Style - LCI 2021+)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/8NCB0Jc.jpeg' },
  { id: 447, brand: 'BMW', compat: ['G30', 'G38'], category: 'Front Lips', title: 'BMW G30 / G38 5-Series Carbon Front Lip (FD Style - LCI 2021+)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/VHs2EJ2.jpeg' },
  { id: 448, brand: 'BMW', compat: ['G30', 'G38'], category: 'Side Skirts', title: 'BMW G30 / G38 5-Series Carbon Side Skirt Extensions (A Style)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/odMJzTN.jpeg' },
  { id: 449, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (M5 Style - Pre-LCI 2018-2020)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/FLG3avD.jpeg' },
  { id: 450, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser With LED Brake Light (CH Style - Pre-LCI 2018-2020)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/CzDQ3ab.jpeg' },
  { id: 451, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (K Style - Pre-LCI 2018-2020)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/xLPDwwQ.jpeg' },
  { id: 452, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (A Style - Pre-LCI 2018-2020)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/7du8uxL.jpeg' },
  { id: 453, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (MP Style - Pre-LCI 2018-2020)', price: '$829 USD', saved: '$3xdunRZ.jpeg' },
  { id: 454, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (3D Style - Pre-LCI 2018-2020)', price: '$879 USD', saved: '$205 USD', image: 'https://i.imgur.com/UgAKqxd.jpeg' },
  { id: 455, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Exhaust Muffler Tips (S Style - Pre-LCI 2018-2020)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/UdsaUOt.jpeg' },
  { id: 456, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Spoiler (M5 Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/aPFeoWF.jpeg' },
  { id: 457, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Front Fender Side Vent Accents', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/0mVSHTD.jpeg' },
  { id: 458, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Spoiler (CS Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/wFVT0Vg.jpeg' },
  { id: 459, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Rear Bumper Side Splitters (PSM Style)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/sV3Aw6h.jpeg' },
  { id: 460, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Spoiler (PRO Style)', price: '$429 USD', saved: '$105 USD', image: 'https://i.imgur.com/kACpBYY.jpeg' },
  { id: 461, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Spoiler (M4 Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/hNvb9bQ.jpeg' },
  { id: 462, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Roof Spoiler (M5 Style)', price: '$559 USD', saved: '$105 USD', image: 'https://i.imgur.com/wrjnx1t.jpeg' },
  { id: 463, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Rear Bumper Side Splitters (FD Style)', price: '$329 USD', saved: '$105 USD', image: 'https://i.imgur.com/DeL9jfg.jpeg' },
  { id: 464, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Spoiler (PSM Style)', price: '$429 USD', saved: '$105 USD', image: 'https://i.imgur.com/JLf4ZyX.jpeg' },
  { id: 465, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Spoilers', title: 'BMW G30 / G38 5-Series Carbon Rear Spoiler (MP Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/ezNjFAh.jpeg' },
  { id: 466, brand: 'BMW', compat: ['G30', 'G38'], category: 'Other', title: 'BMW G30 / G38 5-Series Carbon Front Bumper Foglight Canard Accents', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/gJuOlKO.jpeg' },
  { id: 467, brand: 'BMW', compat: ['G30', 'G38'], category: 'Mirror Covers', title: 'BMW G30 / G38 5-Series Carbon Horn-Style Side Mirror Covers (Pre-LCI 2018-2020)', price: '$299 USD', saved: '$105 USD', image: 'https://i.imgur.com/23mril1.jpeg' },
  { id: 468, brand: 'BMW', compat: ['G30', 'G38'], category: 'Rear Diffusers', title: 'BMW G30 / G38 5-Series Carbon Rear Diffuser (FD Style - Pre-LCI 2018-2020)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/FJcr9gB.jpeg' },

  // === BMW G22 4-Series 專屬集群 ===
  { id: 473, brand: 'BMW', compat: ['G22'], category: 'Front Lips', title: 'BMW G22 4-Series Carbon Front Lip (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/jYplbKa.jpeg' },
  { id: 474, brand: 'BMW', compat: ['G22'], category: 'Front Lips', title: 'BMW G22 4-Series Carbon Front Lip (FD Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/1mWx6Kc.jpeg' },
  { id: 475, brand: 'BMW', compat: ['G22'], category: 'Side Skirts', title: 'BMW G22 4-Series Carbon Side Skirt Extensions (MP Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/Algh4RE.jpeg' },
  { id: 476, brand: 'BMW', compat: ['G22'], category: 'Rear Diffusers', title: 'BMW G22 4-Series Carbon Rear Diffuser Assembly (MP Style)', price: '$789 USD', saved: '$205 USD', image: 'https://i.imgur.com/FBCDble.jpeg' },
  { id: 477, brand: 'BMW', compat: ['G22'], category: 'Rear Spoilers', title: 'BMW G22 4-Series Carbon Rear Trunk Spoiler (M4 Style Spec)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/hNvb9bQ.jpeg' },

  // === BMW X5 (G05) 高端 LD Style 空力集群 (2019+) ===
  { id: 478, brand: 'BMW', compat: ['G05'], category: 'Other', title: 'BMW X5 G05 Premium LD Style Full Widebody Aerodynamic Conversion Kit', price: '$6129 USD', saved: '$460 USD', image: 'https://i.imgur.com/dFcvBvU.jpeg' },
  { id: 479, brand: 'BMW', compat: ['G05'], category: 'Other', title: 'BMW X5 G05 Gloss Black Center Kidney Grilles (LD Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/xABZWqH.jpeg' },
  { id: 480, brand: 'BMW', compat: ['G05'], category: 'Mirror Covers', title: 'BMW X5 G05 Carbon Fiber Side Mirror Covers (LD Style)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/l3ATcGE.jpeg' },
  { id: 481, brand: 'BMW', compat: ['G05'], category: 'Rear Spoilers', title: 'BMW X5 G05 Carbon Fiber Rear Roof Spoiler Wing (LD Style)', price: '$1029 USD', saved: '$205 USD', image: 'https://i.imgur.com/C7I5y1x.jpeg' },
  { id: 482, brand: 'BMW', compat: ['G05'], category: 'Other', title: 'BMW X5 G05 Carbon Fiber Trunk Mid-Wing Spoiler (LD Style)', price: '$629 USD', saved: '$105 USD', image: 'https://i.imgur.com/PoiU4Id.jpeg' },
  { id: 483, brand: 'BMW', compat: ['G05'], category: 'Hood', title: 'BMW X5 G05 Custom Carbon Fiber Engine Hood Panel (LD Style)', price: '$1729 USD', saved: '$360 USD', image: 'https://i.imgur.com/VXTZofR.jpeg' },
  { id: 484, brand: 'BMW', compat: ['G05'], category: 'Side Skirts', title: 'BMW X5 G05 Carbon Fiber Side Skirt Extensions Set (LD Style)', price: '$1729 USD', saved: '$205 USD', image: 'https://i.imgur.com/QdVcOYt.jpeg' },
  { id: 485, brand: 'BMW', compat: ['G05'], category: 'Front Lips', title: 'BMW X5 G05 Carbon Fiber Front Bumper Lip Spoiler (LD Style)', price: '$1899 USD', saved: '$205 USD', image: 'https://i.imgur.com/HXmiPzy.jpeg' },
  { id: 486, brand: 'BMW', compat: ['G05'], category: 'Rear Diffusers', title: 'BMW X5 G05 Carbon Fiber Rear Bumper Diffuser Lip Assembly (LD Style)', price: '$2829 USD', saved: '$360 USD', image: 'https://i.imgur.com/t951QSZ.jpeg' },

  // === BMW 2-Series (G42) 高端 MP Style 空力集群 ===
  { id: 487, brand: 'BMW', compat: ['G42'], category: 'Front Lips', title: 'BMW 2-Series G42 M-Sport Carbon Fiber Front Bumper Lip Spoiler (MP Style)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/r3lM2q5.png' },
  { id: 488, brand: 'BMW', compat: ['G42'], category: 'Side Skirts', title: 'BMW 2-Series G42 M-Sport Carbon Fiber Side Skirt Extensions (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/u1pZ5m3.png' },
  { id: 489, brand: 'BMW', compat: ['G42'], category: 'Rear Diffusers', title: 'BMW 2-Series G42 M-Sport Carbon Fiber Rear Bumper Diffuser Lip (MP Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/D3ijydV.png' },
  { id: 490, brand: 'BMW', compat: ['G42'], category: 'Rear Spoilers', title: 'BMW 2-Series G42 Carbon Fiber Rear Trunk Spoiler Wing (MP Style)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/VbceBPP.png' },
  { id: 491, brand: 'BMW', compat: ['G42'], category: 'Mirror Covers', title: 'BMW 2-Series G42 Carbon Fiber Side Mirror Covers (OEM Style)', price: '$399 USD', saved: '$105 USD', image: 'https://i.imgur.com/cl9rMj8.png' },
  { id: 492, brand: 'BMW', compat: ['G42'], category: 'Other', title: 'BMW 2-Series G42 Full Carbon Fiber Seat Back Shell Covers Set (MP Style)', price: '$579 USD', saved: '$105 USD', image: 'https://i.imgur.com/tBgaY9N.png' },
  { id: 493, brand: 'BMW', compat: ['G42'], category: 'Mirror Covers', title: 'BMW 2-Series G42 Carbon Fiber M-Look Horn Style Side Mirror Covers', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/NXOB9qY.png' },

  // === BMW X5 (G05) 高端碳纖改裝集群 ===
  { id: 494, brand: 'BMW', compat: ['G05'], category: 'Mirror Covers', title: 'BMW X5 G05 Carbon Fiber Side Mirror Covers (M-Horn Style Spec)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/JI0enbP.jpeg' },
  { id: 495, brand: 'BMW', compat: ['G05'], category: 'Other', title: 'BMW X5 G05 Premium Full Carbon Fiber Aerodynamic Body Kit Package (MP Style)', price: '$2129 USD', saved: '$460 USD', image: 'https://i.imgur.com/OgCoVGr.jpeg' },
  { id: 496, brand: 'BMW', compat: ['G05'], category: 'Other', title: 'BMW X5 G05 To X5M Look Full Aerodynamic Conversion Bumper Body Kit Package', price: '$2129 USD', saved: '$460 USD', image: 'https://i.imgur.com/qnxYLzW.jpeg' },
  { id: 497, brand: 'BMW', compat: ['G05'], category: 'Front Lips', title: 'BMW X5 G05 Carbon Fiber Front Bumper Lip Spoiler (CH Style - Only For X5M Look Aftermarket Bumper Setup)', price: '$679 USD', saved: '$205 USD', image: 'https://i.imgur.com/phZCCGq.jpeg' },
  { id: 498, brand: 'BMW', compat: ['G05'], category: 'Other', title: 'BMW X5 G05 Gloss Black Front Center Kidney Grille (Dual Slat Sport Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/VnGDFcY.jpeg' },
  { id: 499, brand: 'BMW', compat: ['G05'], category: 'Rear Spoilers', title: 'BMW X5 G05 Carbon Fiber Roof Spoiler Wing (CH Style)', price: '$499 USD', saved: '$105 USD', image: 'https://i.imgur.com/rr86o7N.jpeg' },
  { id: 500, brand: 'BMW', compat: ['G05'], category: 'Rear Spoilers', title: 'BMW X5 G05 Carbon Fiber Mid-Trunk Spoiler Wing (CH Style)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/K1yPODD.jpeg' },
  { id: 501, brand: 'BMW', compat: ['G05'], category: 'Rear Diffusers', title: 'BMW X5 G05 Carbon Fiber Rear Bumper Diffuser Lip (CH Style)', price: '$729 USD', saved: '$205 USD', image: 'https://i.imgur.com/mMKj9VF.jpeg' },
  { id: 502, brand: 'BMW', compat: ['G05'], category: 'Side Skirts', title: 'BMW X5 G05 Carbon Fiber Side Skirt Extensions (CH Style)', price: '$729 USD', saved: '$205 USD', image: 'https://i.imgur.com/7YPBO5i.jpeg' },
  { id: 503, brand: 'BMW', compat: ['G05'], category: 'Front Lips', title: 'BMW X5 G05 Carbon Fiber Double-Layer Front Bumper Lip Spoiler (CH Style)', price: '$729 USD', saved: '$205 USD', image: 'https://i.imgur.com/M4i0s8k.jpeg' },

  // === BMW X7 (G07) 奢華黑武士改裝集群 ===
  { id: 504, brand: 'BMW', compat: ['G07'], category: 'Front Lips', title: 'BMW X7 G07 Carbon Fiber Double-Layer Front Bumper Lip Spoiler (Black Shadow Style)', price: '$799 USD', saved: '$205 USD', image: 'https://i.imgur.com/ilzJa4U.jpeg' },
  { id: 505, brand: 'BMW', compat: ['G07'], category: 'Side Skirts', title: 'BMW X7 G07 Carbon Fiber Side Skirt Extensions (Black Shadow Style)', price: '$849 USD', saved: '$205 USD', image: 'https://i.imgur.com/Zdo9v4q.jpeg' },
  { id: 506, brand: 'BMW', compat: ['G07'], category: 'Rear Diffusers', title: 'BMW X7 G07 Carbon Fiber Rear Bumper Diffuser Lip (Black Shadow Style)', price: '$799 USD', saved: '$205 USD', image: 'https://i.imgur.com/BFc4xtr.jpeg' },
  { id: 507, brand: 'BMW', compat: ['G07'], category: 'Front Lips', title: 'BMW X7 G07 Carbon Fiber Front Bumper Lip Spoiler (Black Shadow Style)', price: '$799 USD', saved: '$205 USD', image: 'https://i.imgur.com/fqqOpFL.jpeg' },
  { id: 508, brand: 'BMW', compat: ['G07'], category: 'Other', title: 'BMW X7 G07 Black Shadow Style Full Aerodynamic Body Kit Conversion Package (Includes Front Lip, Rear Diffuser, Side Skirts, Grille, Mirror Covers)', price: '$3049 USD', saved: '$650 USD', image: 'https://i.imgur.com/jJe73da.jpeg' },
  { id: 509, brand: 'BMW', compat: ['G07'], category: 'Mirror Covers', title: 'BMW X7 G07 Carbon Fiber Side Mirror Covers (M-Horn Style Spec)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/Z9eH3ii.jpeg' },
  { id: 510, brand: 'BMW', compat: ['G07'], category: 'Other', title: 'BMW X7 G07 Gloss Black Front Center Kidney Grille (Shadow Stealth Edition)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/1cy3XMr.jpeg' },
  { id: 511, brand: 'BMW', compat: ['G07'], category: 'Rear Spoilers', title: 'BMW X7 G07 Carbon Fiber Roof Spoiler Wing (Black Shadow Style)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/5iUOQjC.jpeg' },

  // === BMW X6 (G06) 頂級 LD Style 改裝集群 ===
  { id: 512, brand: 'BMW', compat: ['G06'], category: 'Other', title: 'BMW X6 G06 Gloss Black Front Center Kidney Grille (LD Style)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/TS4p0a1.png' },
  { id: 513, brand: 'BMW', compat: ['G06'], category: 'Other', title: 'BMW X6 G06 Carbon Fiber Fender Vent Air Outlet Trim Covers (LD Style)', price: '$749 USD', saved: '$205 USD', image: 'https://i.imgur.com/ryD0WFD.png' },
  { id: 514, brand: 'BMW', compat: ['G06'], category: 'Mirror Covers', title: 'BMW X6 G06 Carbon Fiber Side Mirror Covers (M-Horn Style Spec)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/ohFemUT.png' },
  { id: 515, brand: 'BMW', compat: ['G06'], category: 'Hood', title: 'BMW X6 G06 Custom Carbon Fiber Engine Hood Bonnet (LD Style)', price: '$2199 USD', saved: '$550 USD', image: 'https://i.imgur.com/T6n3aCL.png' },
  { id: 516, brand: 'BMW', compat: ['G06'], category: 'Rear Spoilers', title: 'BMW X6 G06 Carbon Fiber Roof Spoiler Wing (LD Style)', price: '$909 USD', saved: '$205 USD', image: 'https://i.imgur.com/zoK23xn.png' },
  { id: 517, brand: 'BMW', compat: ['G06'], category: 'Rear Spoilers', title: 'BMW X6 G06 Carbon Fiber Mid-Trunk Spoiler Wing (PSM Style)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/AjlizkU.jpeg' },
  { id: 518, brand: 'BMW', compat: ['G06'], category: 'Rear Spoilers', title: 'BMW X6 G06 Carbon Fiber Rear Upper Roof Wing Spoiler (H Style - Universal Fit)', price: '$469 USD', saved: '$105 USD', image: 'https://i.imgur.com/YmMOQ5a.jpeg' },

  // === BMW 4 Series Gran Coupe (G26) Carbon Fiber MP Style Aerodynamics ===
  { id: 521, brand: 'BMW', compat: ['G26'], category: 'Front Lips', title: 'BMW 4 Series Gran Coupe G26 Carbon Fiber Front Lip Spoiler (MP Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/ldw5BBm.jpeg' },
  { id: 522, brand: 'BMW', compat: ['G26'], category: 'Rear Spoilers', title: 'BMW 4 Series Gran Coupe G26 Carbon Fiber Trunk Spoiler (MP Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/F3pOYIv.jpeg' },
  { id: 523, brand: 'BMW', compat: ['G26'], category: 'Rear Diffusers', title: 'BMW 4 Series Gran Coupe G26 Carbon Fiber Rear Diffuser Lip (MP Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/HIr9I4M.jpeg' },
  { id: 524, brand: 'BMW', compat: ['G26'], category: 'Side Skirts', title: 'BMW 4 Series Gran Coupe G26 Carbon Fiber Side Skirt Extensions (MP Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/wlnU5C8.jpeg' }
];
