/**
 * 🛠️ KINGZCARBON 核心外觀數據庫 (最新標準分流外掛數據庫檔案)
 */ 

// 1. 底盤代號與品牌自動綁定集群
const chassisMapping = {
  'BMW': ['F80 M3', 'F82 / F83 M4', 'F87 M2 / M2C', 'G80 M3', 'G82 M4', 'G20 / G28 3-Series', 'F34 3-Series GT', 'F90 M5', 'F06 / F12 / F13 M6', 'G87 M2', 'F97 X3M / F98 X4M'],    'Audi': ['8V RS3', '8Y RS3'],
    'Toyota': ['A90 Supra'],
    'Nissan': ['R35 GTR']
};

// 2. 核心商品全庫存陣列 (1.8X倍率精算售價 + 免運優惠標籤)
const exteriorDatabase = [
    // === 16 款「三廂車通用尾翼」系列 ===
    { id: 1, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (MAD Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/fR7SeNc.jpeg' },
    { id: 2, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (V Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/vFV5lxE.jpeg' },
    { id: 3, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (MP Style V1)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/ZVmHmeP.jpeg' },
    { id: 4, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (GTS Style V2)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/0klVC3p.jpeg' },
    { id: 5, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (GTS Style Camp V1)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/XVhbNNW.jpeg' },
    { id: 6, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (MP Style V2)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/kpiLpBo.jpeg' },
    { id: 7, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (ADRO Style V1)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/zSVbO3j.jpeg' },
    { id: 8, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (ADRO Style V2)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/2DrL2yG.jpeg' },
    { id: 9, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (3D Style)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/ivKopn7.jpeg' },
    { id: 10, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (PAK Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/tidCxay.jpeg' },
    { id: 11, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (IMP Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/ca5e5FT.jpeg' },
    { id: 12, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (GTC Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/4Lc2T9P.jpeg' },
    { id: 13, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (AP Style)', price: '$1079 USD', saved: '$205 USD', image: 'https://i.imgur.com/ImwNbve.jpeg' },
    { id: 14, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (Voltex Double Deck Style)', price: '$1009 USD', saved: '$205 USD', image: 'https://i.imgur.com/dGUm4SW.jpeg' },
    { id: 15, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (Verus Style)', price: '$1899 USD', saved: '$205 USD', image: 'https://i.imgur.com/jacxe3o.jpeg' },
    { id: 16, brand: 'All', compat: ['All'], category: 'Rear Spoilers', title: 'Universal Sedan Carbon Rear Spoiler (CH Style)', price: '$1969 USD', saved: '$205 USD', image: 'https://i.imgur.com/wBkLp0g.jpeg' },

    // === BMW G80 M3 / G82 M4 高性能集群 ===
    { id: 17, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (R44 Style)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/jigDsLH.jpeg' },
    { id: 18, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (A Style)', price: '$1179 USD', saved: '$205 USD', image: 'https://i.imgur.com/KnTzjy0.jpeg' },
    { id: 19, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Side Fender Vent Accents (CH Style)', price: '$359 USD', saved: '$105 USD', image: 'https://i.imgur.com/n5AEPtd.jpeg' },
    { id: 20, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (MP Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/iiGKyb6.jpeg' },
    { id: 21, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (V Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/a5aBM5i.jpeg' },
    { id: 22, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (CSL Style)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/9AcReRW.jpeg' },
    { id: 23, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (R44 Gen 2 Style)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/ByUEuXQ.jpeg' },
    { id: 24, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (CT Style)', price: '$1009 USD', saved: '$205 USD', image: 'https://i.imgur.com/vEYjveG.jpeg' },
    { id: 25, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bonnet Hood Vent Accents', price: '$409 USD', saved: '$105 USD', image: 'https://i.imgur.com/tSTrM6q.jpeg' },
    { id: 26, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Engine Bay Full Carbon Fiber Cover', price: '$699 USD', saved: '$105 USD', image: 'https://i.imgur.com/orpeM2F.jpeg' },
    { id: 27, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Heavy-Duty Underbody Oil Cooler Guard Panel', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/UTzEdPU.jpeg' },
    { id: 28, brand: 'BMW', compat: ['G80'], category: 'Trunk', title: 'BMW G80 M3 Dedicated Carbon Fiber Trunk Lid (CSL Style)', price: '$1969 USD', saved: '$360 USD', image: 'https://i.imgur.com/ZpmJzpj.jpeg' },
    { id: 29, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Fender', title: 'BMW G80 M3 / G82 M4 Lightweight Carbon Fiber Front Fenders', price: '$1789 USD', saved: '$105 USD', image: 'https://i.imgur.com/kXYhH7S.jpeg' },
    { id: 30, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Fender', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Fenders with Cooling Vents', price: '$1759 USD', saved: '$105 USD', image: 'https://i.imgur.com/ihsn0vH.jpeg' },
    { id: 31, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 Lightweight Carbon Fiber Hood (CSL Style)', price: '$2049 USD', saved: '$360 USD', image: 'https://i.imgur.com/BtKvfx5.jpeg' },
    { id: 32, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Transparent Hood (Glass Style)', price: '$2049 USD', saved: '$360 USD', image: 'https://i.imgur.com/idX3wMy.jpeg' },
    { id: 33, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Hood (ALP Style)', price: '$1009 USD', saved: '$360 USD', image: 'https://i.imgur.com/nfBDqcu.jpeg' },
    { id: 34, brand: 'BMW', compat: ['G80', 'G82'], category: 'Hood', title: 'BMW G80 M3 / G82 M4 High-Clearance Carbon Fiber Hood (Power Style)', price: '$2189 USD', saved: '$360 USD', image: 'https://i.imgur.com/kl6mQRr.jpeg' },
    { id: 35, brand: 'BMW', compat: ['G80', 'G82'], category: 'Mirror Covers', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Side Mirror Covers', price: '$499 USD', saved: '$105 USD', image: 'https://i.imgur.com/XRVthP9.jpeg' },
    { id: 36, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Fiber Roof Antenna Overlay Cover', price: '$179 USD', saved: '$105 USD', image: 'https://i.imgur.com/bCGcpVd.jpeg' },
    { id: 37, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (ALP Style)', price: '$1009 USD', saved: '$105 USD', image: 'https://i.imgur.com/OFDFqg1.jpeg' },
    { id: 38, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (ST Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/ORFs7UH.jpeg' },
    { id: 39, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (V Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/77Bs79b.jpeg' },
    { id: 40, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Kidney Grilles (CSL Style)', price: '$589 USD', saved: '$105 USD', image: 'https://i.imgur.com/0J5Vefg.jpeg' },
    { id: 41, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (PSM Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/Op8zNEZ.jpeg' },
    { id: 42, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (OEM Style)', price: '$369 USD', saved: '$205 USD', image: 'https://i.imgur.com/phEwENP.jpeg' },
    { id: 44, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (Adro Style)', price: '$1309 USD', saved: '$205 USD', image: 'https://i.imgur.com/3Q1vnvf.jpeg' },
    { id: 45, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (B Style)', price: '$1339 USD', saved: '$205 USD', image: 'https://i.imgur.com/TTf8aSs.jpeg' },
    { id: 46, brand: 'BMW', compat: ['G20', 'G28', 'G80'], category: 'Rear Spoilers', title: 'BMW G Gen 3-Series & G80 M3 Carbon Rear Spoiler (M3 Style)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/9iAsTaX.jpeg' },
    { id: 47, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Spoilers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Spoiler (V Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/0yd8I34.jpeg' },
    { id: 48, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser Center Trim (OEM Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/Hd1iBrU.jpeg' },
    { id: 49, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Bumper Side Splitters (OEM Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/XXCIPz2.jpeg' },
    { id: 50, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Bumper Side Splitters (MP Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/WB3C1jT.jpeg' },
    { id: 51, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (RSC Style)', price: '$1339 USD', saved: '$205 USD', image: 'https://i.imgur.com/ehgesTm.jpeg' },
    { id: 52, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (PSM Style)', price: '$1309 USD', saved: '$205 USD', image: 'https://i.imgur.com/fjH1Zlg.jpeg' },
    { id: 53, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser & Side Extension Kit (R44 Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/uj8qAK0.jpeg' },
    { id: 54, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser With F1 LED Light (CH Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/N7XyZ43.jpeg' },
    { id: 55, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (3D Style)', price: '$1049 USD', saved: '$205 USD', image: 'https://i.imgur.com/IIM1cPU.jpeg' },
    { id: 56, brand: 'BMW', compat: ['G80', 'G82'], category: 'Rear Diffusers', title: 'BMW G80 M3 / G82 M4 Carbon Rear Diffuser (MP Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/YOGJco1.jpeg' },
    { id: 57, brand: 'BMW', compat: ['G80', 'G82'], category: 'Side Skirts', title: 'BMW G80 M3 / G82 M4 Carbon Side Skirts (3D Style)', price: '$1009 USD', saved: '$205 USD', image: 'https://i.imgur.com/Kx7oESN.jpeg' },
    { id: 58, brand: 'BMW', compat: ['G80', 'G82'], category: 'Side Skirts', title: 'BMW G80 M3 / G82 M4 Carbon Side Skirts (MP Style)', price: '$979 USD', saved: '$205 USD', image: 'https://i.imgur.com/nxiIjdT.jpeg' },
    { id: 59, brand: 'BMW', compat: ['G80', 'G82'], category: 'Side Skirts', title: 'BMW G80 M3 / G82 M4 Carbon Side Skirts (R44 Style)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/WolcNCI.jpeg' },
    { id: 60, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Side Fender Vent Accents (MP Style)', price: '$359 USD', saved: '$105 USD', image: 'https://i.imgur.com/lW5rPRF.jpeg' },
    { id: 61, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Bumper Side Vent Inlets (R44 Style)', price: '$579 USD', saved: '$105 USD', image: 'https://i.imgur.com/HyD7HrL.jpeg' },
    { id: 62, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Front Bumper Side Vent Inlets (MP Style)', price: '$489 USD', saved: '$105 USD', image: 'https://i.imgur.com/5K4Ua4r.jpeg' },
    { id: 63, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (AC Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/dcRet1W.jpeg' },
    { id: 64, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (3D Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/cGNekA8.jpeg' },
    { id: 65, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (GT Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/tvR6Zj1.jpeg' },
    { id: 66, brand: 'BMW', compat: ['G80', 'G82'], category: 'Other', title: 'BMW G80 M3 / G82 M4 Carbon Bumper Front Canards (MP Style)', price: '$319 USD', saved: '$105 USD', image: 'https://i.imgur.com/bxBYUhW.jpeg' },
    { id: 67, brand: 'BMW', compat: ['G80', 'G82'], category: 'Front Lips', title: 'BMW G80 M3 / G82 M4 Carbon Front Lip (3D Style)', price: '$1009 USD', saved: '$205 USD', image: 'https://i.imgur.com/W4MqFSy.jpeg' },

    // === BMW 3 Series G20 G28 底盤專屬集群 ===
    { id: 68, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (T Style - 2020-2022 M Sport Package Only)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/IC8cBeD.jpeg' },
    { id: 69, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 LCI Carbon Front Lip (AO Style - Facelift 2023-2025)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/jPFPGY8.jpeg' },
    { id: 70, brand: 'BMW', compat: ['G20', 'G28'], category: 'Trunk', title: 'BMW 3-Series G20 / G28 Carbon Fiber Trunk Lid (CSL Style - 2021-2023)', price: '$2049 USD', saved: '$360 USD', image: 'https://i.imgur.com/zuDUGl1.jpeg' },
    { id: 71, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW 3-Series G20 / G28 Carbon Fiber Transparent Hood (Glass Style)', price: '$1389 USD', saved: '$360 USD', image: 'https://i.imgur.com/2Nlrn8F.jpeg' },
    { id: 72, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW 3-Series G20 / G28 Carbon Fiber Hood (C Style)', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/YFQpKgO.jpeg' },
    { id: 73, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW 3-Series G20 / G28 Carbon Fiber Hood (MBJ Style)', price: '$1169 USD', saved: '$360 USD', image: 'https://i.imgur.com/LJJqU3F.jpeg' },
    { id: 74, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW 3-Series G20 / G28 Carbon Fiber Hood (IMP Style)', price: '$1169 USD', saved: '$360 USD', image: 'https://i.imgur.com/cS9kfOe.jpeg' },
    { id: 75, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW 3-Series G20 / G28 Carbon Fiber Hood (CS Style - 2020-2023)', price: '$1169 USD', saved: '$360 USD', image: 'https://i.imgur.com/Rs3ttkE.jpeg' },
    { id: 76, brand: 'BMW', compat: ['G20', 'G28'], category: 'Hood', title: 'BMW 3-Series G20 / G28 Carbon Fiber Hood (GTS Style - 2020-2023)', price: '$1169 USD', saved: '$360 USD', image: 'https://i.imgur.com/HbC0fsO.jpeg' },
    { id: 77, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Fender', title: 'BMW 3-Series G20 / G28 Carbon Fender Panels with Cooling Vents (2020-2023)', price: '$839 USD', saved: '$105 USD', image: 'https://i.imgur.com/qPdIi4S.jpeg' },
    { id: 78, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (GTS Style)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/rrSx9BJ.jpeg' },
    { id: 79, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (Hollow Style)', price: '$339 USD', saved: '$205 USD', image: 'https://i.imgur.com/TDk5zWz.jpeg' },
    { id: 80, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (PSM Style)', price: '$339 USD', saved: '$205 USD', image: 'https://i.imgur.com/2VwgxRl.jpeg' },
    { id: 81, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (PRO Style)', price: '$339 USD', saved: '$205 USD', image: 'https://i.imgur.com/BPXFu8t.jpeg' },
    { id: 82, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (CS Style)', price: '$319 USD', saved: '$205 USD', image: 'https://i.imgur.com/9pP6fHG.jpeg' },
    { id: 83, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (M4 Style)', price: '$319 USD', saved: '$205 USD', image: 'https://i.imgur.com/iNAbRto.jpeg' },
    { id: 84, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (MP Style)', price: '$319 USD', saved: '$205 USD', image: 'https://i.imgur.com/AN0iLGW.jpeg' },
    { id: 85, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Spoilers', title: 'BMW 3-Series G20 / G28 Carbon Rear Spoiler (M Style)', price: '$319 USD', saved: '$205 USD', image: 'https://i.imgur.com/GiDRDzM.jpeg' },
    { id: 86, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3-Series G20 / G28 Full Carbon Front Grille Surround', price: '$269 USD', saved: '$105 USD', image: 'https://i.imgur.com/PeTFuJC.jpeg' },
    { id: 87, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 LCI Carbon Rear Bumper Side Splitters (AD Style - Facelift 2023-2025)', price: '$409 USD', saved: '$205 USD', image: 'https://i.imgur.com/s1gcZQw.jpeg' },
    { id: 88, brand: 'BMW', compat: ['G20', 'G28'], category: 'Mirror Covers', title: 'BMW 3-Series G20 / G28 Carbon Fiber M-Horn Style Side Mirror Covers', price: '$219 USD', saved: '$105 USD', image: 'https://i.imgur.com/HG4BaJP.jpeg' },
    { id: 89, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Bumper Side Splitters (FD Style - 2020-2022)', price: '$369 USD', saved: '$205 USD', image: 'https://i.imgur.com/MjmvnMi.jpeg' },
    { id: 90, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Bumper Vent Canard Accents (2020-2022)', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/zFUTZef.jpeg' },
    { id: 91, brand: 'BMW', compat: ['G20', 'G28'], category: 'Other', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Bumper Vent Canard Accents (T Style - 2020-2022 M Sport Package Only)', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/DuHQbcB.jpeg' },
    { id: 92, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Diffuser (GS Style - 2020-2022 M Sport Package Only)', price: '$669 USD', saved: '$205 USD', image: 'https://i.imgur.com/ODgjmsh.jpeg' },
    { id: 93, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Diffuser With F1 LED Light (T Style - 2020-2022 M Sport Package Only)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/4Auntu2.jpeg' },
    { id: 94, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Diffuser With F1 LED Light (K Style - 2020-2022 M Sport Package Only)', price: '$549 USD', saved: '$205 USD', image: 'https://i.imgur.com/OByrF6v.jpeg' },
    { id: 95, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Diffuser With F1 LED Light (CH Style - 2020-2022 M Sport Package Only)', price: '$629 USD', saved: '$205 USD', image: 'https://i.imgur.com/JXJxyFw.jpeg' },
    { id: 96, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Rear Diffuser (MP Style - 2020-2022 M Sport Package Only)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/ntTqekE.jpeg' },
    { id: 97, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 LCI Carbon Rear Diffuser (V Style - Facelift 2023-2025)', price: '$779 USD', saved: '$205 USD', image: 'https://i.imgur.com/OJBi0r7.jpeg' },
    { id: 98, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 LCI Carbon Rear Diffuser With F1 LED Light (T Style - Facelift 2023-2025)', price: '$709 USD', saved: '$205 USD', image: 'https://i.imgur.com/TPsT4JY.jpeg' },
    { id: 99, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 LCI Carbon Rear Diffuser With F1 LED Light (MP Style - Facelift 2023-2025)', price: '$549 USD', saved: '$205 USD', image: 'https://i.imgur.com/8rXGorU.jpeg' },
    { id: 100, brand: 'BMW', compat: ['G20', 'G28'], category: 'Rear Diffusers', title: 'BMW 3-Series G20 / G28 LCI Carbon Rear Diffuser With F1 LED Light (F Style - Facelift 2023-2025)', price: '$779 USD', saved: '$205 USD', image: 'https://i.imgur.com/ruwYIJV.jpeg' },
    { id: 101, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3-Series G20 / G28 Carbon Side Skirt Extensions (AD Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/WTiNf0P.jpeg' },
    { id: 102, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3-Series G20 / G28 Carbon Side Skirt Extensions (AD Style - M Sport Package Only)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/fsDPXjT.jpeg' },
    { id: 103, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3-Series G20 / G28 Carbon Side Skirt Extensions (T Style - M Sport Package Only)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/Z62I1zx.jpeg' },
    { id: 104, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3-Series G20 / G28 Carbon Side Skirt Extensions (3D Style - M Sport Package Only)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/TiGoNqM.jpeg' },
    { id: 105, brand: 'BMW', compat: ['G20', 'G28'], category: 'Side Skirts', title: 'BMW 3-Series G20 / G28 Carbon Side Skirt Extensions (MP Style - M Sport Package Only)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/xlFBJuB.jpeg' },
    { id: 106, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (AC Style - 2020-2022 M Sport Package Only)', price: '$529 USD', saved: '$205 USD', image: 'https://i.imgur.com/ADriIfS.jpeg' },
    { id: 107, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (CC Style - 2020-2022 M Sport Package Only)', price: '$529 USD', saved: '$205 USD', image: 'https://i.imgur.com/LgVCizS.jpeg' },
    { id: 108, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (AK Style - 2020-2022 M Sport Package Only)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/HeJjeEW.jpeg' },
    { id: 109, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (T Style - 2020-2022 M Sport Package Only)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/QjLVrN6.jpeg' },
    { id: 110, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (MP Style - 2020-2022 M Sport Package Only)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/GxgFiz8.jpeg' },
    { id: 111, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (A Style - 2020-2022)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/OT95bxj.jpeg' },
    { id: 112, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 Pre-LCI Carbon Front Lip (FD Style - 2020-2022)', price: '$439 USD', saved: '$205 USD', image: 'https://i.imgur.com/1r36ytA.jpeg' },
    { id: 113, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 LCI Carbon Front Lip (MP Style - Facelift 2023-2025)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/iLY6zUA.jpeg' },
    { id: 114, brand: 'BMW', compat: ['G20', 'G28'], category: 'Front Lips', title: 'BMW 3-Series G20 / G28 LCI Carbon Front Lip (3D Style - Facelift 2023-2025)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/DnW9hY4.jpeg' },

    // === 原有 F80/F82/F83 M3/M4 專屬集群數據 ===
    { id: 115, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (PSM Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/qrnGuXy.png' },
    { id: 116, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (R Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/F3Hd0r2.png' },
    { id: 117, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (3D Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/CoCsiSq.png' },
    { id: 118, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Side Skirts', title: 'BMW F80/F82 M3/M4 Carbon Side Skirts (Blade Style)', price: '$439 USD', saved: '$205 USD', image: 'https://i.imgur.com/qEVNTeI.png' },
    { id: 119, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (V Style)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/t6UEZip.png' },
    { id: 120, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (AC Style)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/v9j4bly.png' },
    { id: 121, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Splitters (AC Style Lite Edition)', price: '$359 USD', saved: '$205 USD', image: 'https://i.imgur.com/twBj4wn.png' },
    { id: 122, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (PSM Style)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/pyEwfHG.png' },
    { id: 123, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (PSM Dual-Layer Style)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/45wbJ8B.png' },
    { id: 124, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (CS Style)', price: '$459 USD', saved: '$205 USD', image: 'https://i.imgur.com/6lnCcNx.png' },
    { id: 125, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (MP Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/L8Tt0vX.png' },
    { id: 126, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (R Style)', price: '$439 USD', saved: '$205 USD', image: 'https://i.imgur.com/aBCtbi6.png' },
    { id: 127, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (Varis Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/9scjvNX.png' },
    { id: 128, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (Laptorr Style)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/eCVCTCY.png' },
    { id: 129, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (3D Style)', price: '$439 USD', saved: '$205 USD', image: 'https://i.imgur.com/HMLHfl9.png' },
    { id: 130, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Front Lips', title: 'BMW F80/F82 M3/M4 Carbon Front Lip (GT4 Style)', price: '$569 USD', saved: '$205 USD', image: 'https://i.imgur.com/EaAeqv2.png' },
    { id: 131, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (V Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/mkbH1tR.png' },
    { id: 132, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (PSM Style With LED Light)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/Mg3BpAO.png' },
    { id: 133, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (3D Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/3yXUq9r.png' },
    { id: 134, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (CH Style With LED Light)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/rIPpydQ.png' },
    { id: 135, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (Varis Style)', price: '$1119 USD', saved: '$205 USD', image: 'https://i.imgur.com/z3on1NN.png' },
    { id: 136, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Diffusers', title: 'BMW F80/F82 M3/M4 Carbon Rear Diffuser (PSM Style)', price: '$759 USD', saved: '$205 USD', image: 'https://i.imgur.com/2Wp3vLo.png' },
    { id: 137, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Spoilers', title: 'BMW F80/F82 M3/M4 Carbon Rear Spoiler (PSM Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/59AHaeO.png' },
    { id: 138, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Spoilers', title: 'BMW F80/F82 M3/M4 Carbon Rear Spoiler (CS Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/eZgut4k.png' },
    { id: 139, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Rear Spoilers', title: 'BMW F80/F82 M3/M4 Carbon Rear Spoiler (M4 Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/TwmQcsa.png' },
    { id: 140, brand: 'BMW', compat: ['F82', 'F83'], category: 'Trunk', title: 'BMW F82 M4 Carbon Fiber Trunk Lid (OEM Style)', price: '$1009 USD', saved: '$360 USD', image: 'https://i.imgur.com/7DCoR72.png' },
    { id: 141, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Hood', title: 'BMW F80/F82 M3/M4 Carbon Fiber Transparent Hood (Glass Style)', price: '$1229 USD', saved: '$360 USD', image: 'https://i.imgur.com/lzoObzG.png' },
    { id: 142, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Hood', title: 'BMW F80/F82 M3/M4 Carbon Fiber Hood (GTS Style)', price: '$1009 USD', saved: '$360 USD', image: 'https://i.imgur.com/HYcDgsl.png' },
    { id: 143, brand: 'BMW', compat: ['F82', 'F83'], category: 'Trunk', title: 'BMW F82 M4 Carbon Fiber Trunk Lid (CSL Style)', price: '$1229 USD', saved: '$360 USD', image: 'https://i.imgur.com/LP5wTIr.png' },
    { id: 144, brand: 'BMW', compat: ['F82', 'F83'], category: 'Front Fender', title: 'BMW F82 M4 Lightweight Carbon Fiber Front Fenders', price: '$1019 USD', saved: '$105 USD', image: 'https://i.imgur.com/d51eFkh.png' },
    { id: 145, brand: 'BMW', compat: ['F80'], category: 'Front Fender', title: 'BMW F80 M3 Lightweight Carbon Fiber Front Fenders', price: '$1019 USD', saved: '$105 USD', image: 'https://i.imgur.com/MulsV31.png' },
    { id: 146, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Mirror Covers', title: 'BMW F80/F82 M3/M4 Carbon Fiber Horn-Style Mirror Covers', price: '$249 USD', saved: '$105 USD', image: 'https://i.imgur.com/wQQt4zz.png' },
    { id: 147, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Fiber Canards (C Style)', price: '$249 USD', saved: '$105 USD', image: 'https://i.imgur.com/A26hT46.png' },
    { id: 148, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Front Bumper Splitters (CH Style)', price: '$339 USD', saved: '$105 USD', image: 'https://i.imgur.com/1ju5fcm.png' },
    { id: 149, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Fiber Front Canards (CH Style)', price: '$249 USD', saved: '$105 USD', image: 'https://i.imgur.com/NwBBP29.png' },
    { id: 150, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Customizable Carbon Fiber Exhaust Tips', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/eBqLfC3.png' },
    { id: 151, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Full Carbon Fiber Front Kidney Grilles', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/8Q0W43Q.png' },
    { id: 152, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Full Carbon Fiber Seat Back Panels', price: '$499 USD', saved: '$105 USD', image: 'https://i.imgur.com/FZMPLBY.png' },
    { id: 153, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Bumper Canards (GT4 Style)', price: '$419 USD', saved: '$105 USD', image: 'https://i.imgur.com/rS2y3tE.png' },
    { id: 154, brand: 'BMW', compat: ['F80', 'F82', 'F83'], category: 'Other', title: 'BMW F80/F82 M3/M4 Carbon Fiber Canards (MAD Style)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/R6ar2YY.png' },

    // === BMW F34 3-Series GT 專屬高性能改裝集群 ===
    { id: 155, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (H Style - M Sport Only)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/2Sjg728.jpeg' },
    { id: 156, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (KB Style - M Sport Only)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/rF60O4Q.jpeg' },
    { id: 157, brand: 'BMW', compat: ['F34'], category: 'Side Skirts', title: 'BMW 3-Series GT F34 Carbon Side Skirt Extensions (Blade Style - M Sport Only)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/oBDNsWL.jpeg' },
    { id: 158, brand: 'BMW', compat: ['F34'], category: 'Other', title: 'BMW 3-Series GT F34 Full Carbon Front Kidney Grille (Gloss Finish)', price: '$269 USD', saved: '$105 USD', image: 'https://i.imgur.com/Z6pbdS5.jpeg' },
    { id: 159, brand: 'BMW', compat: ['F34'], category: 'Rear Spoilers', title: 'BMW 3-Series GT F34 Carbon Fiber Rear Spoiler (CH Style)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/7Xs9uvt.jpeg' },
    { id: 160, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (PSM Style - Only for M4 Bumper Setup)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/UPJm10i.jpeg' },
    { id: 161, brand: 'BMW', compat: ['F34'], category: 'Other', title: 'BMW 3-Series GT F34 M4 Conversion Style Front & Rear Bumper Kit', price: '$1339 USD', saved: '$460 USD', image: 'https://i.imgur.com/WFObYaj.jpeg' },
    { id: 162, brand: 'BMW', compat: ['F34'], category: 'Other', title: 'BMW 3-Series GT F34 M-Tech Aero Full Body Kit Expansion Set', price: '$2109 USD', saved: '$460 USD', image: 'https://i.imgur.com/VEAnEuv.jpeg' },
    { id: 163, brand: 'BMW', compat: ['F34'], category: 'Rear Spoilers', title: 'BMW 3-Series GT F34 Carbon Fiber Rear Spoiler (3D Style)', price: '$409 USD', saved: '$205 USD', image: 'https://i.imgur.com/SrvUANj.jpeg' },
    { id: 164, brand: 'BMW', compat: ['F34'], category: 'Mirror Covers', title: 'BMW F34 GT Carbon Fiber M-Horn Style Side Mirror Covers', price: '$219 USD', saved: '$105 USD', image: 'https://i.imgur.com/gu2C4tm.jpeg' },
    { id: 165, brand: 'BMW', compat: ['F34'], category: 'Side Skirts', title: 'BMW 3-Series GT F34 Carbon Side Skirt Extensions (MP Style - M Sport Only)', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/ZGeeSH4.jpeg' },
    { id: 166, brand: 'BMW', compat: ['F34'], category: 'Rear Diffusers', title: 'BMW 3-Series GT F34 Carbon Rear Diffuser (KB Style - M Sport Only)', price: '$739 USD', saved: '$205 USD', image: 'https://i.imgur.com/A101CGQ.jpeg' },
    { id: 167, brand: 'BMW', compat: ['F34'], category: 'Rear Diffusers', title: 'BMW 3-Series GT F34 Carbon Rear Diffuser (M5 Style - M Sport Only)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/db7TcET.jpeg' },
    { id: 168, brand: 'BMW', compat: ['F34'], category: 'Rear Diffusers', title: 'BMW 3-Series GT F34 Carbon Rear Diffuser (MP Style - M Sport Only)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/YYYPekK.jpeg' },
    { id: 169, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (MP Style - M Sport Only)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/u7K4OeW.jpeg' },
    { id: 170, brand: 'BMW', compat: ['F34'], category: 'Front Lips', title: 'BMW 3-Series GT F34 Carbon Front Lip (V Style - M Sport Only)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/7lYwwA5.jpeg' },

    // === BMW F90 M5 高階碳纖維集群 ===
    { id: 171, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (CS Style - 2021-2023 LCI)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/tFHchDh.jpeg' },
    { id: 172, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (RPK Style - 2021-2023 LCI)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/r96qcpJ.jpeg' },
    { id: 173, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ML Style - 2021-2023 LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/fzP1jpU.jpeg' },
    { id: 174, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ST Style - 2021-2023 LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/OBBPP9w.jpeg' },
    { id: 175, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (MT Style - 2021-2023 LCI)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/rTgFK3g.jpeg' },
    { id: 176, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (RPK Style - 2018-2020 Pre-LCI)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/WPTMCJ1.jpeg' },
    { id: 177, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ML Style - 2018-2020 Pre-LCI)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/WTrhymT.jpeg' },
    { id: 178, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (ST Style - 2018-2020 Pre-LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/kdMhLrU.jpeg' },
    { id: 179, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (GTS Style - 2018-2020 Pre-LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/14y1YTq.jpeg' },
    { id: 180, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Carbon Front Bumper Splitters (CH Style - 2018-2020 Pre-LCI)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/VkZXmf6.jpeg' },
    { id: 181, brand: 'BMW', compat: ['F90'], category: 'Side Skirts', title: 'BMW F90 M5 Carbon Side Skirt Extensions (A Style - 2018-2020 Pre-LCI)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/ewakiuf.jpeg' },
    { id: 182, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (C Style - 2018-2020 Pre-LCI)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/3pPus76.jpeg' },
    { id: 183, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (A Style - 2018-2020 Pre-LCI)', price: '$919 USD', saved: '$205 USD', image: 'https://i.imgur.com/nYjkIBA.jpeg' },
    { id: 184, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (M Style - 2018-2020 Pre-LCI)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/uyyduJ3.jpeg' },
    { id: 185, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (3D Style - 2018-2020 Pre-LCI)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/enKJ0Vl.jpeg' },
    { id: 186, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (CS Style - 2018-2020 Pre-LCI)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/kLLBkMl.jpeg' },
    { id: 187, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (PRO Style - 2018-2020 Pre-LCI)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/TIYmlW2.jpeg' },
    { id: 188, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Rear Spoiler (V Style - 2018-2020 Pre-LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/XlxcUb2.jpeg' },
    { id: 189, brand: 'BMW', compat: ['F90'], category: 'Rear Spoilers', title: 'BMW F90 M5 Carbon Roof Spoiler Extension (2018-2023 Universal)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/093hgWX.jpeg' },
    { id: 190, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Full Carbon Front Kidney Grille Surround (2018-2020 Pre-LCI)', price: '$409 USD', saved: '$105 USD', image: 'https://i.imgur.com/pRY6U5L.jpeg' },
    { id: 191, brand: 'BMW', compat: ['F90'], category: 'Mirror Covers', title: 'BMW F90 M5 Full Carbon Fiber Side Mirror Covers (2018-2020 Pre-LCI)', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/YxEwOET.jpeg' },
    { id: 192, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Carbon Rear Bumper Side Splitters (FD Style - 2018-2023 Universal)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/Q17Gz6C.jpeg' },
    { id: 193, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Carbon Rear Bumper Side Splitters (PSM Style - 2018-2023 Universal)', price: '$249 USD', saved: '$105 USD', image: 'https://i.imgur.com/Q17Gz6C.jpeg' },
    { id: 194, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (GTS Style - 2021-2023 LCI)', price: '$649 USD', saved: '$205 USD', image: 'https://i.imgur.com/goNURzx.jpeg' },
    { id: 195, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (P Style - 2021-2023 LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/BBlAbNn.jpeg' },
    { id: 196, brand: 'BMW', compat: ['F90'], category: 'Hood', title: 'BMW F90 M5 Motorsport Transparent Glass Carbon Fiber Hood (2018-2023 Universal)', price: '$2609 USD', saved: '$360 USD', image: 'https://i.imgur.com/zbNygtH.jpeg' },
    { id: 197, brand: 'BMW', compat: ['F90'], category: 'Hood', title: 'BMW F90 M5 Carbon Fiber Ventilated GT Style Hood (2018-2023 Universal)', price: '$2609 USD', saved: '$360 USD', image: 'https://i.imgur.com/V8oJLoN.jpeg' },
    { id: 198, brand: 'BMW', compat: ['F90'], category: 'Hood', title: 'BMW F90 M5 Lightweight CS Style Carbon Fiber Hood (2018-2023 Universal)', price: '$2609 USD', saved: '$360 USD', image: 'https://i.imgur.com/GrDAPGe.jpeg' },
    { id: 199, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Front Bumper Foglight Canard Wings (2018-2020 Pre-LCI)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/Y9gmWEx.jpeg' },
    { id: 200, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Front Bumper Foglight Air Vent Inserts (2021-2023 LCI)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/e6xAqzP.jpeg' },
    { id: 201, brand: 'BMW', compat: ['F90'], category: 'Other', title: 'BMW F90 M5 Full Carbon Front Kidney Grille (2018-2023 Universal)', price: '$279 USD', saved: '$105 USD', image: 'https://i.imgur.com/mNFNJDl.jpeg' },
    { id: 202, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (3D Style - 2018-2020 Pre-LCI)', price: '$619 USD', saved: '$205 USD', image: 'https://i.imgur.com/dTv62IQ.jpeg' },
    { id: 203, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (CH Style - 2018-2020 Pre-LCI)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/Bb9wxj5.jpeg' },
    { id: 204, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (Mode Style - 2018-2020 Pre-LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/7RKq1hO.jpeg' },
    { id: 205, brand: 'BMW', compat: ['F90'], category: 'Rear Diffusers', title: 'BMW F90 M5 Carbon Rear Diffuser (MP Style - 2018-2020 Pre-LCI)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/wk7nE2q.jpeg' },
    { id: 206, brand: 'BMW', compat: ['F90'], category: 'Side Skirts', title: 'BMW F90 M5 Carbon Side Skirt Extensions (MP Style - 2018-2020 Pre-LCI)', price: '$359 USD', saved: '$105 USD', image: 'https://i.imgur.com/95j1OPw.jpeg' },
    { id: 207, brand: 'BMW', compat: ['F90'], category: 'Side Skirts', title: 'BMW F90 M5 Carbon Side Skirt Extensions (3D Style - 2018-2020 Pre-LCI)', price: '$409 USD', saved: '$105 USD', image: 'https://i.imgur.com/Rw9eFCR.jpeg' },
    { id: 208, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (A Style - 2018-2020 Pre-LCI)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/AuFwhXX.jpeg' },
    { id: 209, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (A Style - 2021-2023 LCI)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/xjSweSy.jpeg' },
    { id: 210, brand: 'BMW', compat: ['F90'], category: 'Front Lips', title: 'BMW F90 M5 Carbon Front Lip (3D Style - 2021-2023 LCI)', price: '$599 USD', saved: '$205 USD', image: 'https://i.imgur.com/dFE67jy.jpeg' },

    // === BMW F87 M2 / M2C 高性能碳纖維集群 ===
    { id: 211, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Splitters (MP Style - Pre-LCI & LCI Universal)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/Ny07GSd.png' },
    { id: 212, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (MP Style - Pre-LCI & LCI Universal)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/afytYVv.png' },
    { id: 213, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Competition Carbon Front Lip (3D Style - M2C Exclusive)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/XWupjPZ.png' },
    { id: 214, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (BP Style - Base M2 Exclusive)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/BV8YPLQ.png' },
    { id: 215, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (ST Style - Pre-LCI & LCI Universal)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/BV8YPLQ.png' },
    { id: 216, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (C Style - Pre-LCI & LCI Universal)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/p5CMFMP.png' },
    { id: 217, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Rear Side Splitters (MP Style)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/JCXAOv7.png' },
    { id: 218, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (Blade Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/Qmwmpvm.jpeg' },
    { id: 219, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (MTC Style)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/Q5C6CT9.png' },
    { id: 220, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (CH Style)', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/zx9pWHg.jpeg' },
    { id: 221, brand: 'BMW', compat: ['F87'], category: 'Side Skirts', title: 'BMW F87 M2 / M2C Carbon Side Skirt Extensions (3D Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/rOiLJki.png' },
    { id: 222, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (MP Style)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/zX8nxNw.jpeg' },
    { id: 223, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (AK Style)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/y90SlsZ.jpeg' },
    { id: 224, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser With LED F1 Brake Light (K Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/dYZLdM6.jpeg' },
    { id: 225, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser With LED F1 Brake Light (V Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/ttSh9vG.jpeg' },
    { id: 226, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (MP Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/xohdGJ9.png' },
    { id: 227, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (M4 Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/ceoIcva.jpeg' },
    { id: 228, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (CS Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/gQlMUiB.jpeg' },
    { id: 229, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (PSM Style)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/7pGx6re.jpeg' },
    { id: 230, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Motorsport High-Downforce Carbon Wing (MAD Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/WCmZnCm.jpeg' },
    { id: 231, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Track-Spec Carbon GT Wing (MP Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/EC8vaCO.png' },
    { id: 232, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Racing Carbon GT Wing (V Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/9EX2toR.jpeg' },
    { id: 233, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Front Bumper Side Aero Canard Accents (AC Style)', price: '$259 USD', saved: '$105 USD', image: 'https://i.imgur.com/BtS3hLa.png' },
    { id: 234, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 Carbon Kidney Grilles Trim Set (Base M2 Exclusive)', price: '$269 USD', saved: '$105 USD', image: 'https://i.imgur.com/BRTr42C.jpeg' },
    { id: 235, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Carbon Side Fender Emblem Badges Cover', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/JMZmAvX.jpeg' },
    { id: 236, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Quad Exhaust Carbon Fiber Tips Tailpipe Set (MP Style)', price: '$289 USD', saved: '$105 USD', image: 'https://i.imgur.com/1VcuXq3.jpeg' },
    { id: 237, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Front Grille Full Carbon Surround Shell Cover', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/xu4VPRU.jpeg' },
    { id: 238, brand: 'BMW', compat: ['F87'], category: 'Hood', title: 'BMW F87 M2 / M2C Aggressive Ventilated Carbon Fiber Hood (GTS Style)', price: '$2609 USD', saved: '$360 USD', image: 'https://i.imgur.com/IAEtawk.png' },
    { id: 239, brand: 'BMW', compat: ['F87'], category: 'Trunk', title: 'BMW F87 M2 / M2C Lightweight Full Carbon Fiber Trunk Lid (MP Style)', price: '$1739 USD', saved: '$360 USD', image: 'https://i.imgur.com/ecsJVDD.png' },
    { id: 240, brand: 'BMW', compat: ['F87'], category: 'Mirror Covers', title: 'BMW F87 M2 / M2C Carbon Fiber M-Horn Style Side Mirror Covers', price: '$239 USD', saved: '$105 USD', image: 'https://i.imgur.com/wgjsqEd.jpeg' },
    { id: 241, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 / M2C Full Carbon Performance Bucket Seat Back Shell Covers', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/nbq1B41.jpeg' },
    { id: 242, brand: 'BMW', compat: ['F87'], category: 'Hood', title: 'BMW F87 M2 / M2C Performance Carbon Fiber Hood (MP Style)', price: '$2609 USD', saved: '$360 USD', image: 'https://i.imgur.com/EHGrFiF.png' },
    { id: 243, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 M2C-Look Front Bumper Conversion Upgrade Kit', price: '$609 USD', saved: '$205 USD', image: 'https://i.imgur.com/6VRSdqR.jpeg' },
    { id: 244, brand: 'BMW', compat: ['F87'], category: 'Other', title: 'BMW F87 M2 Front Bumper Foglight Splitter Aero Canards (Base M2 Exclusive)', price: '$269 USD', saved: '$105 USD', image: 'https://i.imgur.com/xYbD2c7.jpeg' },
    { id: 245, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (MTC Style - Pre-LCI & LCI Universal)', price: '$519 USD', saved: '$205 USD', image: 'https://i.imgur.com/cpmRAiq.png' },
    { id: 246, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (CS Style - Pre-LCI & LCI Universal)', price: '$539 USD', saved: '$205 USD', image: 'https://i.imgur.com/4rJ830V.png' },
    { id: 247, brand: 'BMW', compat: ['F87'], category: 'Rear Spoilers', title: 'BMW F87 M2 / M2C Carbon Rear Spoiler (MTC Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/1Km71gQ.jpeg' },
    { id: 248, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (MTC Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/pEnQt7J.jpeg' },
    { id: 249, brand: 'BMW', compat: ['F87'], category: 'Rear Diffusers', title: 'BMW F87 M2 / M2C Carbon Rear Diffuser (V Style)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/RIwtxWF.jpeg' },
    { id: 250, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Competition Carbon Front Lip (V Style - M2C Exclusive)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/tFLu71R.jpeg' },
    { id: 251, brand: 'BMW', compat: ['F87'], category: 'Front Lips', title: 'BMW F87 M2 Carbon Front Lip (V Style - Base M2 Exclusive)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/9uXA05n.jpeg' },

    // === BMW M6 (F06 / F12 / F13) 高階碳纖維集群 ===
    { id: 252, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Other', title: 'BMW F06 / F12 / F13 M6 Full Carbon Front Kidney Grilles', price: '$249 USD', saved: '$105 USD', image: 'https://i.imgur.com/9IRBnUx.jpeg' },
    { id: 253, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Mirror Covers', title: 'BMW F06 / F12 / F13 M6 Carbon Fiber Horn-Style Side Mirror Covers', price: '$229 USD', saved: '$105 USD', image: 'https://i.imgur.com/SK0my1I.jpeg' },
    { id: 254, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Spoilers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Spoiler (V Style)', price: '$419 USD', saved: '$205 USD', image: 'https://i.imgur.com/vouoTh1.jpeg' },
    { id: 255, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Spoilers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Spoiler (MP Style)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/R6mer8u.jpeg' },
    { id: 256, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (PSM Style Heavy Work)', price: '$1269 USD', saved: '$360 USD', image: 'https://i.imgur.com/h4lNVeO.jpeg' },
    { id: 257, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (FD Style Aero Spec)', price: '$719 USD', saved: '$205 USD', image: 'https://i.imgur.com/tyFMQ1I.jpeg' },
    { id: 258, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (V Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/joh6zct.jpeg' },
    { id: 259, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Rear Diffusers', title: 'BMW F06 / F12 / F13 M6 Carbon Rear Diffuser (MP Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/h3dp2PB.jpeg' },
    { id: 260, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Side Skirts', title: 'BMW F06 / F12 / F13 M6 Carbon Side Skirt Extensions (V Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/3l623si.jpeg' },
    { id: 261, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (3D Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/dX7qmVa.png' },
    { id: 262, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (RPK Style)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/LeQOgzU.jpeg' },
    { id: 263, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (V1 Spec)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/nV7zHgU.jpeg' },
    { id: 264, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (V2 Spec)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/oFvbqi3.jpeg' },
    { id: 265, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (MP Style)', price: '$619 USD', saved: '$205 USD', image: 'https://i.imgur.com/fqPHyl7.jpeg' },
    { id: 266, brand: 'BMW', compat: ['F06', 'F12', 'F13'], category: 'Front Lips', title: 'BMW F06 / F12 / F13 M6 Carbon Front Lip (H Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/Z9XYXPk.jpeg' },
    // === 🌟 NEW AUDIT: BMW G87 M2 專屬高端外觀集群 ===
    { id: 267, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Fiber Rear Diffuser (V Style Spec)', price: '$1929 USD', saved: '$205 USD', image: 'https://i.imgur.com/ecQWmUG.jpeg' }, // 7500*1.8+1600
    { id: 268, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Full Carbon Fiber Underbody Protection Guard Shield', price: '$909 USD', saved: '$105 USD', image: 'https://i.imgur.com/D1RTfsR.jpeg' }, // 3500*1.8+800
    { id: 269, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (R44 Spec)', price: '$779 USD', saved: '$205 USD', image: 'https://i.imgur.com/iMhXN72.jpeg' }, // 2500*1.8+1600
    { id: 270, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (AD Style Premium)', price: '$1469 USD', saved: '$205 USD', image: 'https://i.imgur.com/0sAyHYF.jpeg' }, // 5500*1.8+1600
    { id: 271, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (MP Style Side Splitters)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/sERjlZE.jpeg' }, // 2600*1.8+1600
    { id: 272, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (TAKD Style Aero)', price: '$1309 USD', saved: '$205 USD', image: 'https://i.imgur.com/LjMsluP.jpeg' }, // 4800*1.8+1600
    { id: 273, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (V Style Premium)', price: '$1589 USD', saved: '$205 USD', image: 'https://i.imgur.com/lwOSimple.jpeg' }, // 6000*1.8+1600
    { id: 274, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (OEM Style)', price: '$849 USD', saved: '$205 USD', image: 'https://i.imgur.com/x8D3tHi.png' }, // 2800*1.8+1600
    { id: 275, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (TAKD Style)', price: '$1309 USD', saved: '$205 USD', image: 'https://i.imgur.com/yJeMbve.jpeg' },
    { id: 276, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Rear Spoiler (MP Style Small V1)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/24LpsnD.jpeg' }, // 800*1.8+1600
    { id: 277, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Track-Spec Motorsport Carbon Wing With Integrated LED Light (GT Style)', price: '$3209 USD', saved: '$360 USD', image: 'https://i.imgur.com/mjndrQw.jpeg' }, // 12000*1.8+3600
    { id: 278, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Roof Spoiler Extension Wing', price: '$849 USD', saved: '$205 USD', image: 'https://i.imgur.com/t8vtvJv.jpeg' },
    { id: 279, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Front Bumper Foglight Vent Aero Canards (SQ Style)', price: '$749 USD', saved: '$105 USD', image: 'https://i.imgur.com/nZOUqnB.jpeg' }, // 2800*1.8+800
    { id: 280, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Grille Center Mesh (MP Style)', price: '$619 USD', saved: '$105 USD', image: 'https://i.imgur.com/kIckmNs.jpeg' }, // 2200*1.8+800
    { id: 281, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Front Grille Center Mesh (S Style Performance)', price: '$749 USD', saved: '$105 USD', image: 'https://i.imgur.com/MRcJZCa.jpeg' },
    { id: 282, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Front Bumper Side Aero Canard Accents (MP Style)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/VsvOLgn.jpeg' }, // 1500*1.8+800
    { id: 283, brand: 'BMW', compat: ['G87'], category: 'Mirror Covers', title: 'BMW G87 M2 Full Carbon Fiber Side Mirror Covers (OEM Plus Spec)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/O8EkXwy.jpeg' }, // 1800*1.8+800
    { id: 284, brand: 'BMW', compat: ['G87'], category: 'Front Fender', title: 'BMW G87 M2 Lightweight Carbon Fiber Fenders Side Panel Set (V Style)', price: '$1919 USD', saved: '$360 USD', image: 'https://i.imgur.com/WRIPi8i.jpeg' }, // 特大件超重物流 6800*1.8+3600
    { id: 285, brand: 'BMW', compat: ['G87'], category: 'Hood', title: 'BMW G87 M2 Aggressive Ventilated Carbon Fiber Hood Panel (V Style)', price: '$2469 USD', saved: '$360 USD', image: 'https://i.imgur.com/LTNNyce.jpeg' }, // 9200*1.8+2800 = 19360 -> $2469
    { id: 286, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Fiber Roof Antenna Fin Overlay Cover', price: '$219 USD', saved: '$105 USD', image: 'https://i.imgur.com/g7nS68W.jpeg' }, // 500*1.8+800
    { id: 287, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Executive Carbon Fiber Trunk Racing Wing (MP Style Large V2)', price: '$1049 USD', saved: '$205 USD', image: 'https://i.imgur.com/hVzDOc7.jpeg' }, // 3000*1.8+1600
    { id: 288, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (MP Style Performance Aero)', price: '$849 USD', saved: '$205 USD', image: 'https://i.imgur.com/yFTJjof.jpeg' }, // 2800*1.8+1600
    { id: 289, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (V Style Spec High-Gloss)', price: '$1359 USD', saved: '$205 USD', image: 'https://i.imgur.com/WtIw3cs.jpeg' }, // 5000*1.8+1600
    { id: 290, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Full Carbon Fiber Performance Bucket Seat Back Shell Covers', price: '$979 USD', saved: '$105 USD', image: 'https://i.imgur.com/bkA7j0G.jpeg' }, // 3800*1.8+800
    { id: 291, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Rear Bumper Side Aero Canard Accents (MP Style)', price: '$449 USD', saved: '$105 USD', image: 'https://i.imgur.com/dfZlsSX.jpeg' },
    { id: 292, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Front Bumper Lower Side Splitter Canards (TAKD Style)', price: '$409 USD', saved: '$105 USD', image: 'https://i.imgur.com/aZ1hTbT.jpeg' }, // 1300*1.8+800
    { id: 293, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Carbon Grille Center Trim (CSL Heritage Style)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/oqlKta6.jpeg' }, // 1800*1.8+800
    { id: 294, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Rear Bumper Wheel Vent Accents Inserts (MP Style Cover)', price: '$519 USD', saved: '$105 USD', image: 'https://i.imgur.com/oAykQQg.jpeg' },
    { id: 295, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Front Bumper Side Mesh Intakes Air Vent Grille Trim (MP Style)', price: '$659 USD', saved: '$105 USD', image: 'https://i.imgur.com/f2789UJ.jpeg' }, // 2400*1.8+800
    { id: 296, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Elite Carbon Fiber Trunk Racing Wing (CH Style High-Downforce)', price: '$1999 USD', saved: '$205 USD', image: 'https://i.imgur.com/aZU5nMF.jpeg' }, // 7800*1.8+1600 -> 15640 -> $1999
    { id: 297, brand: 'BMW', compat: ['G87'], category: 'Rear Spoilers', title: 'BMW G87 M2 Carbon Rear Spoiler (VS Style Aerodynamics)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/nOPJrY2.jpeg' },
    { id: 298, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (CH Style Spec)', price: '$1589 USD', saved: '$205 USD', image: 'https://i.imgur.com/qqyLiNa.jpeg' }, // 6000*1.8+1600
    { id: 299, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Center-Exhaust Upgrade Carbon Rear Diffuser (MP Special Center-Exit Setup Only)', price: '$899 USD', saved: '$205 USD', image: 'https://i.imgur.com/jaCIzaI.png' }, // 3000*1.8+1600
    { id: 300, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (ADRO Style Track Edition)', price: '$1129 USD', saved: '$205 USD', image: 'https://i.imgur.com/LRWYtpE.jpeg' }, // 4000*1.8+1600
    { id: 301, brand: 'BMW', compat: ['G87'], category: 'Front Fender', title: 'BMW G87 M2 Lightweight Carbon Fiber Fenders Side Panel Set (N Carbon Racing)', price: '$1919 USD', saved: '$360 USD', image: 'https://i.imgur.com/MAedKMC.jpeg' },
    { id: 302, brand: 'BMW', compat: ['G87'], category: 'Side Skirts', title: 'BMW G87 M2 Carbon Side Skirt Extensions (R44 Aero Design)', price: '$1009 USD', saved: '$205 USD', image: 'https://i.imgur.com/Va84zJf.jpeg' }, // 3500*1.8+1600
    { id: 303, brand: 'BMW', compat: ['G87'], category: 'Other', title: 'BMW G87 M2 Engine Bay Full Carbon Fiber Engine Cover Overlay Trim', price: '$659 USD', saved: '$105 USD', image: 'https://i.imgur.com/IRQYqJ2.jpeg' },
    { id: 304, brand: 'BMW', compat: ['G87'], category: 'Front Lips', title: 'BMW G87 M2 Carbon Front Lip (TAKD Style Premium Aero)', price: '$1029 USD', saved: '$205 USD', image: 'https://i.imgur.com/GEuNQqf.jpeg' }, // 3600*1.8+1600
    { id: 305, brand: 'BMW', compat: ['G87'], category: 'Rear Diffusers', title: 'BMW G87 M2 Carbon Rear Diffuser (R44 Aero Design)', price: '$1079 USD', saved: '$205 USD', image: 'https://i.imgur.com/cTTXChh.jpeg' }, // 3800*1.8+1600
// === 🌟 RE-AUDIT: BMW F97 X3M / F98 X4M 高階高性能集群 ===
    { id: 306, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (E Style V1)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/Qp26Ucs.png' }, // 1500*1.8+1600
    { id: 307, brand: 'BMW', compat: ['F97'], category: 'Rear Diffusers', title: 'BMW F97 X3M Carbon Rear Diffuser With LED F1 Brake Light (CH Style - X3M Exclusive)', price: '$699 USD', saved: '$205 USD', image: 'https://i.imgur.com/mJHGEgL.png' }, // 2600*1.8+1600
    { id: 308, brand: 'BMW', compat: ['F98'], category: 'Rear Diffusers', title: 'BMW F98 X4M Carbon Rear Diffuser (3D Style - X4M Exclusive)', price: '$739 USD', saved: '$205 USD', image: 'https://i.imgur.com/7ybk6Gs.png' }, // 2800*1.8+1600
    { id: 309, brand: 'BMW', compat: ['F97', 'F98'], category: 'Mirror Covers', title: 'BMW F97 X3M / F98 X4M Carbon Fiber M-Horn Style Side Mirror Covers', price: '$219 USD', saved: '$105 USD', image: 'https://i.imgur.com/J4OJoPq.png' }, // 500*1.8+800
    { id: 310, brand: 'BMW', compat: ['F97'], category: 'Rear Spoilers', title: 'BMW F97 X3M Carbon Mid Roof Spoiler (C Style - X3M Exclusive)', price: '$409 USD', saved: '$205 USD', image: 'https://i.imgur.com/IkXjzUG.png' }, // 600*1.8+1600
    { id: 311, brand: 'BMW', compat: ['F97'], category: 'Rear Spoilers', title: 'BMW F97 X3M Carbon Mid Roof Spoiler (E Style - X3M Exclusive)', price: '$409 USD', saved: '$205 USD', image: 'https://i.imgur.com/SC4AiAX.png' }, // 👈 這裡已精準修正為 X3M 專用
    { id: 312, brand: 'BMW', compat: ['F98'], category: 'Rear Spoilers', title: 'BMW F98 X4M Carbon Rear Trunk Spoiler (PSM Style - X4M Exclusive)', price: '$409 USD', saved: '$205 USD', image: 'https://i.imgur.com/PfPGQ0i.png' },
    { id: 313, brand: 'BMW', compat: ['F97', 'F98'], category: 'Hood', title: 'BMW F97 X3M / F98 X4M Aggressive Carbon Fiber Hood (CS Style)', price: '$1709 USD', saved: '$360 USD', image: 'https://i.imgur.com/fMKG5ic.png' }, // 5000*1.8+2800 = 11800 -> $1709
    { id: 314, brand: 'BMW', compat: ['F97', 'F98'], category: 'Other', title: 'BMW F97 X3M / F98 X4M Full Carbon Front Kidney Grille Surround', price: '$409 USD', saved: '$105 USD', image: 'https://i.imgur.com/t06JjcD.png' }, // 750*1.8+800
    { id: 315, brand: 'BMW', compat: ['F98'], category: 'Rear Spoilers', title: 'BMW F98 X4M Carbon Rear Trunk Spoiler (CS Style - X4M Exclusive)', price: '$389 USD', saved: '$205 USD', image: 'https://i.imgur.com/psd2Vo6.png' }, // 500*1.8+1600
    { id: 316, brand: 'BMW', compat: ['F97'], category: 'Rear Spoilers', title: 'BMW F97 X3M Carbon Upper Roof Wing Extension (MP Style - X3M Exclusive)', price: '$479 USD', saved: '$205 USD', image: 'https://i.imgur.com/M3dVnX2.png' }, // 1000*1.8+1600
    { id: 317, brand: 'BMW', compat: ['F98'], category: 'Rear Diffusers', title: 'BMW F98 X4M Carbon Rear Diffuser With LED F1 Brake Light (CH Style - X4M Exclusive)', price: '$589 USD', saved: '$205 USD', image: 'https://i.imgur.com/xmKhwNR.png' }, // 2000*1.8+1600
    { id: 318, brand: 'BMW', compat: ['F97'], category: 'Rear Diffusers', title: 'BMW F97 X3M Carbon Rear Diffuser (E Style - X3M Exclusive)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/MXBlH46.png' }, // 1800*1.8+1600
    { id: 319, brand: 'BMW', compat: ['F97'], category: 'Rear Diffusers', title: 'BMW F97 X3M Carbon Rear Diffuser (3D Style - X3M Exclusive)', price: '$739 USD', saved: '$205 USD', image: 'https://i.imgur.com/6KOfURl.png' }, // 2800*1.8+1600
    { id: 320, brand: 'BMW', compat: ['F97', 'F98'], category: 'Side Skirts', title: 'BMW F97 X3M / F98 X4M Carbon Side Skirt Extensions (3D Style)', price: '$499 USD', saved: '$205 USD', image: 'https://i.imgur.com/dkc4UrY.png' }, // 1500*1.8+1600
    { id: 321, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (E Style V2)', price: '$579 USD', saved: '$205 USD', image: 'https://i.imgur.com/NmwTI2A.png' }, // 1600*1.8+1600
    { id: 322, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (JC Style)', price: '$739 USD', saved: '$205 USD', image: 'https://i.imgur.com/QligR0x.png' }, // 2800*1.8+1600
    { id: 323, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (ST Style)', price: '$439 USD', saved: '$205 USD', image: 'https://i.imgur.com/8S8Rv5d.png' }, // 1100*1.8+1600
    { id: 324, brand: 'BMW', compat: ['F97', 'F98'], category: 'Front Lips', title: 'BMW F97 X3M / F98 X4M Carbon Front Lip (3D Style)', price: '$559 USD', saved: '$205 USD', image: 'https://i.imgur.com/PbQ7BUn.png' }  // 1800*1.8+1600
];
